CREATE schema CAFE61
go
--Procedure para limpiar todas las tablas
create PROCEDURE cafe61.LimpiezaEsquema
AS
	IF OBJECT_ID(N'cafe61.ENVIO_MENSAJERIA', N'U') IS NOT NULL  
	   DROP TABLE cafe61.ENVIO_MENSAJERIA;  
	IF OBJECT_ID(N'cafe61.PAQUETE', N'U') IS NOT NULL  
	   DROP TABLE cafe61.PAQUETE;  
	IF OBJECT_ID(N'cafe61.PRODUCTO_PEDIDO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.PRODUCTO_PEDIDO;  
	IF OBJECT_ID(N'cafe61.PRODUCTO_LOCAL', N'U') IS NOT NULL  
	   DROP TABLE cafe61.PRODUCTO_LOCAL;  
	IF OBJECT_ID(N'cafe61.CUPON_PEDIDO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.CUPON_PEDIDO;  
	IF OBJECT_ID(N'cafe61.CUPON_RECLAMO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.CUPON_RECLAMO;  
	IF OBJECT_ID(N'cafe61.CUPON', N'U') IS NOT NULL  
	   DROP TABLE cafe61.CUPON;  
	IF OBJECT_ID(N'cafe61.RECLAMO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.RECLAMO;  
	IF OBJECT_ID(N'cafe61.PEDIDO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.PEDIDO;  
	IF OBJECT_ID(N'cafe61.MEDIO_PAGO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.MEDIO_PAGO;  
	IF OBJECT_ID(N'cafe61.MEDIO_PAGO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.MEDIO_PAGO;  
	IF OBJECT_ID(N'cafe61.ENVIO_PEDIDO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.ENVIO_PEDIDO;  
	IF OBJECT_ID(N'cafe61.LOCAL', N'U') IS NOT NULL  
	   DROP TABLE cafe61.LOCAL;  
	IF OBJECT_ID(N'cafe61.LOCAL_CATEGORIA', N'U') IS NOT NULL  
	   DROP TABLE cafe61.LOCAL_CATEGORIA;  
	IF OBJECT_ID(N'cafe61.REPARTIDOR_LOCALIDAD', N'U') IS NOT NULL  
	   DROP TABLE cafe61.REPARTIDOR_LOCALIDAD;  
	IF OBJECT_ID(N'cafe61.REPARTIDOR', N'U') IS NOT NULL  
	   DROP TABLE cafe61.REPARTIDOR;  
	IF OBJECT_ID(N'cafe61.LOCALIDAD', N'U') IS NOT NULL  
	   DROP TABLE cafe61.LOCALIDAD;  
	IF OBJECT_ID(N'cafe61.PROVINCIA', N'U') IS NOT NULL  
	   DROP TABLE cafe61.PROVINCIA;  
	IF OBJECT_ID(N'cafe61.PEDIDO_ESTADO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.PEDIDO_ESTADO;  
	IF OBJECT_ID(N'cafe61.LOCAL_TIPO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.LOCAL_TIPO;  
	IF OBJECT_ID(N'cafe61.PRODUCTO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.PRODUCTO;  
	IF OBJECT_ID(N'cafe61.TIPO_MOVILIDAD', N'U') IS NOT NULL  
	   DROP TABLE cafe61.TIPO_MOVILIDAD;  
	IF OBJECT_ID(N'cafe61.ENVIO_RECORRIDO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.ENVIO_RECORRIDO;  
	IF OBJECT_ID(N'cafe61.PAQUETE_TIPO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.PAQUETE_TIPO;  
	IF OBJECT_ID(N'cafe61.ENVIO_MENSAJERIA_ESTADO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.ENVIO_MENSAJERIA_ESTADO;  
	IF OBJECT_ID(N'cafe61.MARCA_TARJETA', N'U') IS NOT NULL  
	   DROP TABLE cafe61.MARCA_TARJETA;  
	IF OBJECT_ID(N'cafe61.TIPO_MEDIO_PAGO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.TIPO_MEDIO_PAGO;  
	IF OBJECT_ID(N'cafe61.DIRECCION_USUARIO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.DIRECCION_USUARIO;  
	IF OBJECT_ID(N'cafe61.USUARIO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.USUARIO;  
	IF OBJECT_ID(N'cafe61.TIPO_RECLAMO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.TIPO_RECLAMO;  
	IF OBJECT_ID(N'cafe61.RECLAMO_ESTADO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.RECLAMO_ESTADO;  
	IF OBJECT_ID(N'cafe61.OPERADOR_RECLAMO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.OPERADOR_RECLAMO;  
go
--No tienen FK
--Operador Reclamo
CREATE PROCEDURE cafe61.operador_reclamo_crear
as
	CREATE TABLE CAFE61.OPERADOR_RECLAMO(
           OPERADOR_RECLAMO_DNI decimal(18,0),
		   OPERADOR_RECLAMO_NOMBRE nvarchar(255),
           OPERADOR_RECLAMO_APELLIDO nvarchar(255),
           OPERADOR_RECLAMO_TELEFONO decimal(18,0),
           OPERADOR_RECLAMO_DIRECCION nvarchar(255),
           OPERADOR_RECLAMO_MAIL nvarchar(255),
           OPERADOR_RECLAMO_FECHA_NAC date,
		   OPERADOR_CODIGO int IDENTITY(1,1) PRIMARY KEY
		   )
	INSERT INTO CAFE61.OPERADOR_RECLAMO
    SELECT OPERADOR_RECLAMO_DNI,
			OPERADOR_RECLAMO_NOMBRE,
           OPERADOR_RECLAMO_APELLIDO,
           OPERADOR_RECLAMO_TELEFONO,
           OPERADOR_RECLAMO_DIRECCION,
           OPERADOR_RECLAMO_MAIL,
           OPERADOR_RECLAMO_FECHA_NAC
    FROM gd_esquema.Maestra 
	where OPERADOR_RECLAMO_DNI IS NOT NULL AND OPERADOR_RECLAMO_NOMBRE IS NOT NULL AND OPERADOR_RECLAMO_APELLIDO IS NOT NULL
	group by OPERADOR_RECLAMO_DNI,
			OPERADOR_RECLAMO_NOMBRE,
           OPERADOR_RECLAMO_APELLIDO,
           OPERADOR_RECLAMO_TELEFONO,
           OPERADOR_RECLAMO_DIRECCION,
           OPERADOR_RECLAMO_MAIL,
           OPERADOR_RECLAMO_FECHA_NAC
GO
--Reclamo Estado
CREATE PROCEDURE cafe61.reclamo_estado_crear
as
CREATE TABLE CAFE61.RECLAMO_ESTADO(
           RECLAMO_ESTADO nvarchar(50),
		   RECLAMO_ESTADO_CODIGO int IDENTITY(1,1) PRIMARY KEY
		   )
	INSERT INTO CAFE61.RECLAMO_ESTADO
    SELECT DISTINCT(RECLAMO_ESTADO)
    FROM gd_esquema.Maestra
	where RECLAMO_ESTADO IS NOT NULL
GO
--Tipo Reclamo
CREATE PROCEDURE cafe61.tipo_reclamo_crear
as
CREATE TABLE CAFE61.TIPO_RECLAMO(
           TIPO_RECLAMO_DESCRIPCION nvarchar(50),
		   TIPO_RECLAMO_CODIGO int IDENTITY(1,1) PRIMARY KEY
		   )
	INSERT INTO CAFE61.TIPO_RECLAMO
    SELECT DISTINCT(RECLAMO_TIPO)
    FROM gd_esquema.Maestra
	where RECLAMO_TIPO IS NOT NULL
go
-- Usuario
CREATE PROCEDURE cafe61.usuario_crear
as
CREATE TABLE CAFE61.USUARIO(
           USUARIO_NOMBRE nvarchar(255),
		   USUARIO_APELLIDO nvarchar(255),
           USUARIO_DNI decimal(18,0),
           USUARIO_FECHA_REGISTRO datetime2(3),
           USUARIO_TELEFONO decimal(18,0),
           USUARIO_MAIL nvarchar(255),
           USUARIO_FECHA_NAC date,
		   USUARIO_CODIGO int IDENTITY(1,1) PRIMARY KEY
		   )
	INSERT INTO CAFE61.USUARIO
    SELECT USUARIO_NOMBRE,
		   USUARIO_APELLIDO,
           USUARIO_DNI,
           USUARIO_FECHA_REGISTRO,
           USUARIO_TELEFONO,
           USUARIO_MAIL,
           USUARIO_FECHA_NAC
    FROM gd_esquema.Maestra 
	where USUARIO_DNI IS NOT NULL AND USUARIO_NOMBRE IS NOT NULL AND USUARIO_APELLIDO IS NOT NULL
	GROUP BY USUARIO_NOMBRE,
		   USUARIO_APELLIDO,
           USUARIO_DNI,
           USUARIO_FECHA_REGISTRO,
           USUARIO_TELEFONO,
           USUARIO_MAIL,
           USUARIO_FECHA_NAC
GO
--Tipo Medio de pago
create procedure cafe61.tipo_medio_pago_crear
as
CREATE TABLE CAFE61.TIPO_MEDIO_PAGO(
           TIPO_MEDIO_PAGO nvarchar(50),
		   TIPO_MEDIO_PAGO_CODIGO int IDENTITY(1,1) PRIMARY KEY
		   )
	INSERT INTO CAFE61.TIPO_MEDIO_PAGO
    SELECT DISTINCT(MEDIO_PAGO_TIPO)
    FROM gd_esquema.Maestra
	where MEDIO_PAGO_TIPO IS NOT NULL
GO
--Marca Tarjeta
create procedure cafe61.marca_tarjeta_crear
as
CREATE TABLE CAFE61.MARCA_TARJETA(
           MARCA_TARJETA nvarchar(100),
		   MARCA_TARJETA_CODIGO int IDENTITY(1,1) PRIMARY KEY
		   )
	INSERT INTO CAFE61.MARCA_TARJETA
    SELECT DISTINCT(MARCA_TARJETA)
    FROM gd_esquema.Maestra
	where MARCA_TARJETA IS NOT NULL
GO
--Envio Mensajeria estado
create procedure cafe61.envio_mensajeria_estado_crear
as
CREATE TABLE CAFE61.ENVIO_MENSAJERIA_ESTADO(
           ENVIO_MENSAJERIA_ESTADO nvarchar(50),
		   ENVIO_MENSAJERIA_ESTADO_CODIGO int IDENTITY(1,1) PRIMARY KEY
		   )
	INSERT INTO CAFE61.ENVIO_MENSAJERIA_ESTADO
    SELECT DISTINCT(ENVIO_MENSAJERIA_ESTADO)
    FROM gd_esquema.Maestra
	where ENVIO_MENSAJERIA_ESTADO IS NOT NULL
GO
--Paquete Tipo
create procedure cafe61.paquete_tipo_crear
as
CREATE TABLE CAFE61.PAQUETE_TIPO(
           PAQUETE_TIPO nvarchar(50),
		   PAQUETE_TIPO_PRECIO decimal(18,2),
		   PAQUETE_TIPO_CODIGO int IDENTITY(1,1) PRIMARY KEY
		   )
	INSERT INTO CAFE61.PAQUETE_TIPO
    SELECT DISTINCT(PAQUETE_TIPO),
		   PAQUETE_TIPO_PRECIO
    FROM gd_esquema.Maestra
	where PAQUETE_TIPO IS NOT NULL AND PAQUETE_TIPO_PRECIO IS NOT NULL
GO
--Envio Recorrido
create procedure cafe61.envio_recorrido_crear
as
CREATE TABLE CAFE61.ENVIO_RECORRIDO(
           ENVIO_RECORRIDO_DIR_ORIG nvarchar(255),
		   ENVIO_RECORRIDO_DIR_DEST nvarchar(255),
		   ENVIO_RECORRIDO_KM decimal(18,2),
		   ENVIO_RECORRIDO_CODIGO int IDENTITY(1,1) PRIMARY KEY
		   )
	INSERT INTO CAFE61.ENVIO_RECORRIDO
    SELECT ENVIO_MENSAJERIA_DIR_ORIG,
			ENVIO_MENSAJERIA_DIR_DEST,
			ENVIO_MENSAJERIA_KM
    FROM gd_esquema.Maestra
	where ENVIO_MENSAJERIA_DIR_ORIG IS NOT NULL AND ENVIO_MENSAJERIA_DIR_DEST IS NOT NULL AND ENVIO_MENSAJERIA_KM IS NOT NULL
	group by ENVIO_MENSAJERIA_DIR_ORIG,
			ENVIO_MENSAJERIA_DIR_DEST,
			ENVIO_MENSAJERIA_KM
GO
--Provincia
create procedure cafe61.provincia_crear
as
CREATE TABLE CAFE61.PROVINCIA(
           PROVINCIA_NOMBRE nvarchar(255),
		   PROVINCIA_CODIGO int IDENTITY(1,1) PRIMARY KEY
		   )
	INSERT INTO CAFE61.PROVINCIA
    SELECT DISTINCT(ENVIO_MENSAJERIA_PROVINCIA)
    FROM gd_esquema.Maestra
	where ENVIO_MENSAJERIA_PROVINCIA IS NOT NULL
GO
--Tipo Movilidad
create procedure cafe61.tipo_movilidad_crear
as
CREATE TABLE CAFE61.TIPO_MOVILIDAD(
           TIPO_MOVILIDAD_DESCRIPCION nvarchar(50),
		   TIPO_MOVILIDAD_CODIGO int IDENTITY(1,1) PRIMARY KEY
		   )
	INSERT INTO CAFE61.TIPO_MOVILIDAD
    SELECT DISTINCT(REPARTIDOR_TIPO_MOVILIDAD)
    FROM gd_esquema.Maestra
	where REPARTIDOR_TIPO_MOVILIDAD IS NOT NULL
GO
--Producto 
create procedure cafe61.producto_crear
as
CREATE TABLE CAFE61.PRODUCTO(
           PRODUCTO_DESCRIPCION nvarchar(255),
		   PRODUCTO_NOMBRE nvarchar(50),
		   PRODUCTO_CODIGO nvarchar(50) NOT NULL 
		   )
	INSERT INTO CAFE61.PRODUCTO
    SELECT PRODUCTO_LOCAL_DESCRIPCION,
		   PRODUCTO_LOCAL_NOMBRE,
		   PRODUCTO_LOCAL_CODIGO
    FROM gd_esquema.Maestra
	where PRODUCTO_LOCAL_CODIGO IS NOT NULL
	group by PRODUCTO_LOCAL_DESCRIPCION,
		   PRODUCTO_LOCAL_NOMBRE,
		   PRODUCTO_LOCAL_CODIGO

	ALTER TABLE CAFE61.PRODUCTO
	ADD CONSTRAINT PK_PRODUCTO_CODIGO
	PRIMARY KEY (PRODUCTO_CODIGO)
GO
--Local Tipo
create procedure cafe61.local_tipo_crear
as
CREATE TABLE CAFE61.LOCAL_TIPO(
           LOCAL_TIPO_DESCRIPCION nvarchar(50),
		   LOCAL_TIPO_CODIGO int IDENTITY(1,1) PRIMARY KEY
		   )
	INSERT INTO CAFE61.LOCAL_TIPO
    SELECT distinct(LOCAL_TIPO)
    FROM gd_esquema.Maestra
	where LOCAL_TIPO IS NOT NULL
GO
--Pedido Estado
create procedure cafe61.pedido_estado_crear
as
CREATE TABLE CAFE61.PEDIDO_ESTADO(
           PEDIDO_ESTADO nvarchar(50),
		   PEDIDO_ESTADO_CODIGO int IDENTITY(1,1) PRIMARY KEY
		   )
	INSERT INTO CAFE61.PEDIDO_ESTADO
    SELECT distinct(PEDIDO_ESTADO)
    FROM gd_esquema.Maestra
	where PEDIDO_ESTADO IS NOT NULL
GO
-- Tienen FK
-- LOCALIDAD
create procedure cafe61.localidad_crear
as
CREATE TABLE CAFE61.LOCALIDAD(
           LOCALIDAD_DESCRIPCION nvarchar(255),
           LOCALIDAD_PROVINCIA int
		   )
	INSERT INTO CAFE61.LOCALIDAD
	SELECT ENVIO_MENSAJERIA_LOCALIDAD,
		   P.PROVINCIA_CODIGO
	FROM gd_esquema.Maestra as M
		INNER JOIN CAFE61.PROVINCIA AS P
		on M.ENVIO_MENSAJERIA_PROVINCIA = P.PROVINCIA_NOMBRE
		where M.ENVIO_MENSAJERIA_PROVINCIA IS NOT NULL
		group by ENVIO_MENSAJERIA_LOCALIDAD, ENVIO_MENSAJERIA_PROVINCIA, P.PROVINCIA_CODIGO

		-- Añadir una columna de identidad como clave primaria
		ALTER TABLE CAFE61.LOCALIDAD
		ADD LOCALIDAD_CODIGO INT IDENTITY(1,1) PRIMARY KEY;

		-- Agregar la clave foránea a la columna OperadorReclamo
		ALTER TABLE CAFE61.LOCALIDAD
		ADD CONSTRAINT FK_LOCALIDAD_PROVINCIA
		FOREIGN KEY (LOCALIDAD_PROVINCIA)
		REFERENCES CAFE61.PROVINCIA (PROVINCIA_CODIGO); 
go
-- REPARTIDOR
create procedure cafe61.repartidor_crear
as
CREATE TABLE CAFE61.REPARTIDOR(
           REPARTIDOR_NOMBRE nvarchar(255),
           REPARTIDOR_APELLIDO nvarchar(255),
           REPARTIDOR_DNI decimal(18,0),
           REPARTIDOR_TELEFONO decimal(18,0),
           REPARTIDOR_DIRECION nvarchar(255),
	       REPARTIDOR_EMAIL nvarchar(255),
	       REPARTIDOR_FECHA_NAC date,
		   REPARTIDOR_TIPO_MOVILIDAD int,
		   )
	INSERT INTO CAFE61.REPARTIDOR
	SELECT M.REPARTIDOR_NOMBRE,
		   M.REPARTIDOR_APELLIDO,
		   M.REPARTIDOR_DNI,
		   M.REPARTIDOR_TELEFONO,
		   M.REPARTIDOR_DIRECION,
		   M.REPARTIDOR_EMAIL,
		   M.REPARTIDOR_FECHA_NAC,
		   T.TIPO_MOVILIDAD_CODIGO
	FROM gd_esquema.Maestra as M
		INNER JOIN CAFE61.TIPO_MOVILIDAD AS T
		on M.REPARTIDOR_TIPO_MOVILIDAD = T.TIPO_MOVILIDAD_DESCRIPCION
		where M.REPARTIDOR_TIPO_MOVILIDAD IS NOT NULL
		group by  M.REPARTIDOR_NOMBRE,
		   M.REPARTIDOR_APELLIDO,
		   M.REPARTIDOR_DNI,
		   M.REPARTIDOR_TELEFONO,
		   M.REPARTIDOR_DIRECION,
		   M.REPARTIDOR_EMAIL,
		   M.REPARTIDOR_FECHA_NAC,
		   T.TIPO_MOVILIDAD_CODIGO
		-- Añadir una columna de identidad como clave primaria
		ALTER TABLE CAFE61.REPARTIDOR
		ADD REPARTIDOR_CODIGO INT IDENTITY(1,1) PRIMARY KEY;

		-- Agregar la clave foránea a la columna OperadorReclamo
		ALTER TABLE CAFE61.REPARTIDOR
		ADD CONSTRAINT FK_REPARTIDOR_TIPO_MOVILIDAD
		FOREIGN KEY (REPARTIDOR_TIPO_MOVILIDAD)
		REFERENCES CAFE61.TIPO_MOVILIDAD (TIPO_MOVILIDAD_CODIGO);
go
-- REPARTIDOR LOCALIDAD
create procedure cafe61.repartidor_localidad_crear
as
CREATE TABLE CAFE61.REPARTIDOR_LOCALIDAD(
		   LOCALIDAD_CODIGO int,
           REPARTIDOR_CODIGO int
		   )
	INSERT INTO CAFE61.REPARTIDOR_LOCALIDAD
	SELECT L.LOCALIDAD_CODIGO,
		   R.REPARTIDOR_CODIGO
	FROM gd_esquema.Maestra as M
		INNER JOIN CAFE61.LOCALIDAD AS L
		on M.ENVIO_MENSAJERIA_LOCALIDAD = L.LOCALIDAD_DESCRIPCION
		INNER JOIN CAFE61.REPARTIDOR AS R
		on M.REPARTIDOR_APELLIDO = R.REPARTIDOR_APELLIDO AND M.REPARTIDOR_DNI = R.REPARTIDOR_DNI AND M.REPARTIDOR_NOMBRE = R.REPARTIDOR_NOMBRE
		where M.REPARTIDOR_DNI IS NOT NULL AND M.REPARTIDOR_NOMBRE IS NOT NULL AND M.REPARTIDOR_APELLIDO IS NOT NULL AND M.ENVIO_MENSAJERIA_LOCALIDAD IS NOT NULL
		group by M.REPARTIDOR_APELLIDO, 
		M.REPARTIDOR_DNI, 
		M.REPARTIDOR_NOMBRE,
		L.LOCALIDAD_CODIGO,
		R.REPARTIDOR_CODIGO
		
		-- Agregar la clave foránea a la columna LOCALIDAD_CODIGO
		ALTER TABLE CAFE61.REPARTIDOR_LOCALIDAD
		ADD CONSTRAINT FK_LOCALIDAD_CODIGO
		FOREIGN KEY (LOCALIDAD_CODIGO)
		REFERENCES CAFE61.LOCALIDAD (LOCALIDAD_CODIGO);
		-- Agregar la clave foránea a la columna REPARTIDOR CODIG
		ALTER TABLE CAFE61.REPARTIDOR_LOCALIDAD
		ADD CONSTRAINT FK_REPARTIDOR_CODIGO
		FOREIGN KEY (REPARTIDOR_CODIGO)
		REFERENCES CAFE61.REPARTIDOR (REPARTIDOR_CODIGO);
go
-- DIRECCION USUARIO
create procedure cafe61.direccion_usuario_crear
as
CREATE TABLE CAFE61.DIRECCION_USUARIO(
           DIRECCION_USUARIO_NOMBRE nvarchar(50),
           DIRECCION_USUARIO_DIRECCION nvarchar(255),
	       DIRECCION_USUARIO_LOCALIDAD nvarchar(255),
		   DIRECCION_USUARIO_PROVINCIA nvarchar(255),
	       DIRECCION_USUARIO_USUARIO int
		   )
	INSERT INTO CAFE61.DIRECCION_USUARIO
	SELECT DIRECCION_USUARIO_NOMBRE,
		   DIRECCION_USUARIO_DIRECCION,
		   DIRECCION_USUARIO_LOCALIDAD,
		   DIRECCION_USUARIO_PROVINCIA,
		   U.USUARIO_CODIGO
	FROM gd_esquema.Maestra as M
		INNER JOIN CAFE61.USUARIO AS U
		on M.USUARIO_DNI = U.USUARIO_DNI AND M.USUARIO_NOMBRE = U.USUARIO_NOMBRE AND M.USUARIO_APELLIDO = U.USUARIO_APELLIDO
		where M.USUARIO_DNI IS NOT NULL AND M.USUARIO_NOMBRE IS NOT NULL AND M.USUARIO_APELLIDO IS NOT NULL
		group by DIRECCION_USUARIO_NOMBRE,
		   DIRECCION_USUARIO_DIRECCION,
		   DIRECCION_USUARIO_LOCALIDAD,
		   DIRECCION_USUARIO_PROVINCIA,
		   U.USUARIO_CODIGO,
		   M.USUARIO_DNI,
		   M.USUARIO_NOMBRE,
		   M.USUARIO_APELLIDO

		-- Añadir una columna de identidad como clave primaria
		ALTER TABLE CAFE61.DIRECCION_USUARIO
		ADD DIRECCION_USUARIO_CODIGO INT IDENTITY(1,1) PRIMARY KEY;

		-- Agregar la clave foránea a la columna OperadorReclamo
		ALTER TABLE CAFE61.DIRECCION_USUARIO
		ADD CONSTRAINT FK_DIRECCION_USUARIO_USUARIO
		FOREIGN KEY (DIRECCION_USUARIO_USUARIO)
		REFERENCES CAFE61.USUARIO (USUARIO_CODIGO);
go
--LOCAL CATEGORIA
create procedure cafe61.local_categoria_crear
as
CREATE TABLE CAFE61.LOCAL_CATEGORIA(
           LOCAL_CATEGORIA_DESCRIPCION nvarchar(255),
           LOCAL_CATEGORIA_TIPO int
		   )
	INSERT INTO CAFE61.LOCAL_CATEGORIA
	SELECT LOCAL_TIPO,
		   T.LOCAL_TIPO_CODIGO
	FROM gd_esquema.Maestra as M
		INNER JOIN CAFE61.LOCAL_TIPO AS T
		on M.LOCAL_TIPO = T.LOCAL_TIPO_DESCRIPCION
		where M.LOCAL_TIPO IS NOT NULL
		group by LOCAL_TIPO,
		   T.LOCAL_TIPO_CODIGO

		-- Añadir una columna de identidad como clave primaria
		ALTER TABLE CAFE61.LOCAL_CATEGORIA
		ADD LOCAL_CATEGORIA_CODIGO INT IDENTITY(1,1) PRIMARY KEY;

		-- Agregar la clave foránea a la columna OperadorReclamo
		ALTER TABLE CAFE61.LOCAL_CATEGORIA
		ADD CONSTRAINT FK_LOCAL_CATEGORIA_TIPO
		FOREIGN KEY (LOCAL_CATEGORIA_TIPO)
		REFERENCES CAFE61.LOCAL_TIPO (LOCAL_TIPO_CODIGO);
go
--LOCAL
create procedure cafe61.local_crear
as
CREATE TABLE CAFE61.LOCAL(
           LOCAL_NOMBRE nvarchar(50),
		   LOCAL_DESCRIPCION nvarchar(255),
           LOCAL_DIRECCION nvarchar(255),
		   LOCAL_TIPO int,
	       LOCAL_LOCALIDAD nvarchar(255),
		   LOCAL_PROVINCIA nvarchar(255)
		   )
	INSERT INTO CAFE61.LOCAL
	SELECT LOCAL_NOMBRE,
		   LOCAL_DESCRIPCION,
		   LOCAL_DIRECCION,
		   T.LOCAL_TIPO_CODIGO,
		   LOCAL_LOCALIDAD,
		   LOCAL_PROVINCIA
	FROM gd_esquema.Maestra as M
		INNER JOIN CAFE61.LOCAL_TIPO AS T
		on M.LOCAL_TIPO = T.LOCAL_TIPO_DESCRIPCION
		where M.LOCAL_TIPO IS NOT NULL
		group by LOCAL_NOMBRE,
		   LOCAL_DESCRIPCION,
		   LOCAL_DIRECCION,
		   T.LOCAL_TIPO_CODIGO,
		   LOCAL_LOCALIDAD,
		   LOCAL_PROVINCIA

		-- Añadir una columna de identidad como clave primaria
		ALTER TABLE CAFE61.LOCAL
		ADD LOCAL_CODIGO INT IDENTITY(1,1) PRIMARY KEY;

		-- Agregar la clave foránea a la columna OperadorReclamo
		ALTER TABLE CAFE61.LOCAL
		ADD CONSTRAINT FK_LOCAL_TIPO
		FOREIGN KEY (LOCAL_TIPO)
		REFERENCES CAFE61.LOCAL_TIPO (LOCAL_TIPO_CODIGO);
go
-- ENVIO PEDIDO 
create procedure cafe61.envio_pedido_crear
as
CREATE TABLE CAFE61.ENVIO_PEDIDO(
           ENVIO_PEDIDO_DIRECCION_USUARIO int,
		   ENVIO_PEDIDO_REPARTIDOR int,
		   ENVIO_PEDIDO_PEDIDO decimal(18,0),
	       ENVIO_PEDIDO_LOCAL int,
		   ENVIO_PEDIDO_TIEMPO_ESTIMADO_ENTREGA decimal(18,2),
		   ENVIO_PEDIDO_FECHA_ENTREGA datetime,
		   ENVIO_PEDIDO_PRECIO_ENVIO decimal(18,2),
		   ENVIO_PEDIDO_PROPINA decimal(18,2),
		   )
	INSERT INTO CAFE61.ENVIO_PEDIDO
	SELECT DU.DIRECCION_USUARIO_CODIGO,
		   R.REPARTIDOR_CODIGO,
		   PEDIDO_NRO,
		   L.LOCAL_CODIGO,
		   PEDIDO_TIEMPO_ESTIMADO_ENTREGA,
		   PEDIDO_FECHA_ENTREGA,
		   PEDIDO_PRECIO_ENVIO,
		   PEDIDO_PROPINA
	FROM gd_esquema.Maestra as M
		INNER JOIN CAFE61.DIRECCION_USUARIO AS DU
		on M.DIRECCION_USUARIO_NOMBRE = DU.DIRECCION_USUARIO_NOMBRE AND M.DIRECCION_USUARIO_DIRECCION = DU.DIRECCION_USUARIO_DIRECCION
		INNER JOIN CAFE61.REPARTIDOR AS R
		on M.REPARTIDOR_APELLIDO= R.REPARTIDOR_APELLIDO AND M.REPARTIDOR_NOMBRE = R.REPARTIDOR_NOMBRE AND M.REPARTIDOR_DNI= R.REPARTIDOR_DNI
		INNER JOIN CAFE61.LOCAL AS L
		on M.LOCAL_DESCRIPCION = L.LOCAL_DESCRIPCION AND M.LOCAL_NOMBRE = L.LOCAL_NOMBRE AND M.LOCAL_DIRECCION = L.LOCAL_DIRECCION
		where M.DIRECCION_USUARIO_NOMBRE IS NOT NULL AND M.DIRECCION_USUARIO_DIRECCION IS NOT NULL AND M.REPARTIDOR_DNI IS NOT NULL AND M.REPARTIDOR_NOMBRE IS NOT NULL AND M.REPARTIDOR_APELLIDO IS NOT NULL AND M.LOCAL_DESCRIPCION IS NOT NULL AND M.LOCAL_NOMBRE IS NOT NULL AND M.LOCAL_DIRECCION IS NOT NULL
		group by DU.DIRECCION_USUARIO_CODIGO,
		   R.REPARTIDOR_CODIGO,
		   PEDIDO_NRO,
		   L.LOCAL_CODIGO,
		   PEDIDO_TIEMPO_ESTIMADO_ENTREGA,
		   PEDIDO_FECHA_ENTREGA,
		   PEDIDO_PRECIO_ENVIO,
		   PEDIDO_PROPINA,
		   M.DIRECCION_USUARIO_NOMBRE,
		   M.DIRECCION_USUARIO_DIRECCION,
		   M.REPARTIDOR_APELLIDO,
		   M.REPARTIDOR_NOMBRE,
		   M.REPARTIDOR_DNI,
		   M.LOCAL_DESCRIPCION,
		   M.LOCAL_NOMBRE,
		   M.LOCAL_DIRECCION

		-- Añadir una columna de identidad como clave primaria
		ALTER TABLE CAFE61.ENVIO_PEDIDO
		ADD ENVIO_PEDIDO_CODIGO INT IDENTITY(1,1) PRIMARY KEY;

		-- Agregar la clave foránea a la columna OperadorReclamo
		ALTER TABLE CAFE61.ENVIO_PEDIDO
		ADD CONSTRAINT FK_ENVIO_PEDIDO_DIRECCION_USUARIO
		FOREIGN KEY (ENVIO_PEDIDO_DIRECCION_USUARIO)
		REFERENCES CAFE61.DIRECCION_USUARIO (DIRECCION_USUARIO_CODIGO);
		
		ALTER TABLE CAFE61.ENVIO_PEDIDO
		ADD CONSTRAINT FK_ENVIO_PEDIDO_REPARTIDOR
		FOREIGN KEY (ENVIO_PEDIDO_REPARTIDOR)
		REFERENCES CAFE61.REPARTIDOR (REPARTIDOR_CODIGO);

		ALTER TABLE CAFE61.ENVIO_PEDIDO
		ADD CONSTRAINT FK_ENVIO_PEDIDO_DIRECCION_LOCAL
		FOREIGN KEY (ENVIO_PEDIDO_LOCAL)
		REFERENCES CAFE61.LOCAL (LOCAL_CODIGO);
go
-- MEDIO PAGO
create procedure cafe61.medio_pago_crear
as
CREATE TABLE CAFE61.MEDIO_PAGO(
		   MEDIO_PAGO_NRO_TARJETA nvarchar(50),
	       MEDIO_PAGO_TIPO int,
		   MEDIO_PAGO_MARCA_TARJETA int,
		   MEDIO_PAGO_USUARIO INT
		   )
	INSERT INTO CAFE61.MEDIO_PAGO
	SELECT MEDIO_PAGO_NRO_TARJETA,
		   T.TIPO_MEDIO_PAGO_CODIGO,
		   MT.MARCA_TARJETA_CODIGO,
		   U.USUARIO_CODIGO
	FROM gd_esquema.Maestra as M
		INNER JOIN CAFE61.TIPO_MEDIO_PAGO AS T
		on M.MEDIO_PAGO_TIPO = T.TIPO_MEDIO_PAGO
		INNER JOIN CAFE61.MARCA_TARJETA AS MT
		on M.MARCA_TARJETA= MT.MARCA_TARJETA
		INNER JOIN CAFE61.USUARIO AS U
		on M.USUARIO_DNI = U.USUARIO_DNI AND M.USUARIO_NOMBRE = U.USUARIO_NOMBRE AND M.USUARIO_APELLIDO = U.USUARIO_APELLIDO
		where M.USUARIO_DNI IS NOT NULL AND M.USUARIO_NOMBRE IS NOT NULL AND M.USUARIO_APELLIDO IS NOT NULL AND M.MARCA_TARJETA IS NOT NULL AND M.MEDIO_PAGO_TIPO IS NOT NULL
		group by M.MEDIO_PAGO_NRO_TARJETA,
		   M.MEDIO_PAGO_TIPO,
		   M.MARCA_TARJETA,
		   M.USUARIO_DNI,
		   M.USUARIO_NOMBRE,
		   M.USUARIO_APELLIDO, 
		   MT.MARCA_TARJETA_CODIGO,
		   U.USUARIO_CODIGO,
		   T.TIPO_MEDIO_PAGO_CODIGO
		
		-- Añadir una columna de identidad como clave primaria
		ALTER TABLE CAFE61.MEDIO_PAGO
		ADD MEDIO_PAGO_CODIGO INT IDENTITY(1,1) PRIMARY KEY;

		-- Agregar la clave foránea a la columna OperadorReclamo
		ALTER TABLE CAFE61.MEDIO_PAGO
		ADD CONSTRAINT FK_MEDIO_PAGO_USUARIO
		FOREIGN KEY (MEDIO_PAGO_USUARIO)
		REFERENCES CAFE61.USUARIO (USUARIO_CODIGO);
		
		ALTER TABLE CAFE61.MEDIO_PAGO
		ADD CONSTRAINT FK_MEDIO_PAGO_MARCA_TARJETA
		FOREIGN KEY (MEDIO_PAGO_MARCA_TARJETA)
		REFERENCES CAFE61.MARCA_TARJETA (MARCA_TARJETA_CODIGO);

		ALTER TABLE CAFE61.MEDIO_PAGO
		ADD CONSTRAINT FK_MEDIO_PAGO_TIPO
		FOREIGN KEY (MEDIO_PAGO_TIPO)
		REFERENCES CAFE61.TIPO_MEDIO_PAGO (TIPO_MEDIO_PAGO_CODIGO);
go
--PEDIDO
create procedure cafe61.pedido_crear
as
CREATE TABLE CAFE61.PEDIDO(
		   PEDIDO_NUMERO decimal(18,0) NOT NULL ,
	       PEDIDO_FECHA datetime,
		   PEDIDO_USUARIO int,
		   PEDIDO_LOCAL int,
		   PEDIDO_ENVIO_PEDIDO int,
		   PEDIDO_TOTAL_CUPONES decimal(18,2),
		   PEDIDO_TOTAL_PRODUCTOS decimal(18,2),
		   PEDIDO_TARIFA_SERVICIO decimal(18,2),
		   PEDIDO_MEDIO_PAGO int,
		   PEDIDO_TOTAL_SERVICIO decimal(18,2),
		   PEDIDO_OBSERV nvarchar(255),
		   PEDIDO_ESTADO int,
		   PEDIDO_CALIFICACION decimal(18,0)
		   )
	INSERT INTO CAFE61.PEDIDO (PEDIDO_NUMERO,
		   PEDIDO_FECHA,
		   PEDIDO_TOTAL_CUPONES,
		   PEDIDO_TOTAL_PRODUCTOS,
		   PEDIDO_TARIFA_SERVICIO,
		   PEDIDO_TOTAL_SERVICIO,
		   PEDIDO_OBSERV,
		   PEDIDO_CALIFICACION
		   )
	SELECT PEDIDO_NRO,
		   PEDIDO_FECHA,
		   PEDIDO_TOTAL_CUPONES,
		   PEDIDO_TOTAL_PRODUCTOS,
		   PEDIDO_TARIFA_SERVICIO,
		   PEDIDO_TOTAL_SERVICIO,
		   PEDIDO_OBSERV,
		   PEDIDO_CALIFICACION
	FROM gd_esquema.Maestra as M
	where PEDIDO_NRO is not null
	group by PEDIDO_NRO,
		   PEDIDO_FECHA,
		   PEDIDO_TOTAL_CUPONES,
		   PEDIDO_TOTAL_PRODUCTOS,
		   PEDIDO_TARIFA_SERVICIO,
		   PEDIDO_TOTAL_SERVICIO,
		   PEDIDO_OBSERV,
		   PEDIDO_CALIFICACION
-- SE ACTUALIZA EL USUARIO
MERGE cafe61.PEDIDO As PED
USING (SELECT PEDIDO_NRO,
		   PEDIDO_FECHA,
		   PEDIDO_TOTAL_CUPONES,
		   PEDIDO_TOTAL_PRODUCTOS,
		   PEDIDO_TARIFA_SERVICIO,
		   PEDIDO_TOTAL_SERVICIO,
		   PEDIDO_OBSERV,
		   PEDIDO_CALIFICACION,
		   USUARIO_CODIGO
		   FROM gd_esquema.Maestra AS M
		   INNER JOIN cafe61.USUARIO AS U ON M.USUARIO_DNI = U.USUARIO_DNI AND M.USUARIO_APELLIDO = U.USUARIO_APELLIDO
		   WHERE PEDIDO_NRO IS NOT NULL AND M.USUARIO_DNI IS NOT NULL
		   GROUP BY PEDIDO_NRO,
		   PEDIDO_FECHA,
		   PEDIDO_TOTAL_CUPONES,
		   PEDIDO_TOTAL_PRODUCTOS,
		   PEDIDO_TARIFA_SERVICIO,
		   PEDIDO_TOTAL_SERVICIO,
		   PEDIDO_OBSERV,
		   PEDIDO_CALIFICACION,
		  USUARIO_CODIGO) AS M
on PED.PEDIDO_NUMERO = M.PEDIDO_NRO
when matched then
UPDATE SET 
PEDIDO_USUARIO = USUARIO_CODIGO;
-- SE ACTUALIZA EL CODIGO DE LOCAL
MERGE cafe61.PEDIDO As PED
USING (SELECT PEDIDO_NRO,
		   PEDIDO_FECHA,
		   PEDIDO_TOTAL_CUPONES,
		   PEDIDO_TOTAL_PRODUCTOS,
		   PEDIDO_TARIFA_SERVICIO,
		   PEDIDO_TOTAL_SERVICIO,
		   PEDIDO_OBSERV,
		   PEDIDO_CALIFICACION,
		   LOCAL_CODIGO
		   FROM gd_esquema.Maestra AS M
		   INNER JOIN CAFE61.LOCAL AS L
		   on M.LOCAL_DESCRIPCION = L.LOCAL_DESCRIPCION AND M.LOCAL_NOMBRE = L.LOCAL_NOMBRE AND M.LOCAL_DIRECCION = L.LOCAL_DIRECCION
		   WHERE PEDIDO_NRO IS NOT NULL AND M.LOCAL_NOMBRE IS NOT NULL
		   GROUP BY PEDIDO_NRO,
		   PEDIDO_FECHA,
		   PEDIDO_TOTAL_CUPONES,
		   PEDIDO_TOTAL_PRODUCTOS,
		   PEDIDO_TARIFA_SERVICIO,
		   PEDIDO_TOTAL_SERVICIO,
		   PEDIDO_OBSERV,
		   PEDIDO_CALIFICACION,
		  LOCAL_CODIGO) AS M
on PED.PEDIDO_NUMERO = M.PEDIDO_NRO
when matched then
UPDATE SET 
PEDIDO_LOCAL = LOCAL_CODIGO;
-- SE ACTUALIZA EL ENVIO DEL PEDIDO
MERGE cafe61.PEDIDO As PED
USING (SELECT PEDIDO_NRO,
		   PEDIDO_FECHA,
		   PEDIDO_TOTAL_CUPONES,
		   PEDIDO_TOTAL_PRODUCTOS,
		   PEDIDO_TARIFA_SERVICIO,
		   PEDIDO_TOTAL_SERVICIO,
		   PEDIDO_OBSERV,
		   PEDIDO_CALIFICACION,
		   ENVIO_PEDIDO_CODIGO
		   FROM gd_esquema.Maestra AS M
		   INNER JOIN CAFE61.ENVIO_PEDIDO AS E
			on M.PEDIDO_NRO = E.ENVIO_PEDIDO_PEDIDO
		   WHERE PEDIDO_NRO IS NOT NULL
		   GROUP BY PEDIDO_NRO,
		   PEDIDO_FECHA,
		   PEDIDO_TOTAL_CUPONES,
		   PEDIDO_TOTAL_PRODUCTOS,
		   PEDIDO_TARIFA_SERVICIO,
		   PEDIDO_TOTAL_SERVICIO,
		   PEDIDO_OBSERV,
		   PEDIDO_CALIFICACION,
		  ENVIO_PEDIDO_CODIGO) AS M
on PED.PEDIDO_NUMERO = M.PEDIDO_NRO
when matched then
UPDATE SET 
PEDIDO_ENVIO_PEDIDO = ENVIO_PEDIDO_CODIGO;
-- SE ACTUALIZA EL MEDIO DE PAGO
MERGE cafe61.PEDIDO As PED
USING (SELECT PEDIDO_NRO,
		   PEDIDO_FECHA,
		   PEDIDO_TOTAL_CUPONES,
		   PEDIDO_TOTAL_PRODUCTOS,
		   PEDIDO_TARIFA_SERVICIO,
		   PEDIDO_TOTAL_SERVICIO,
		   PEDIDO_OBSERV,
		   PEDIDO_CALIFICACION,
		   MEDIO_PAGO_CODIGO
		   FROM gd_esquema.Maestra AS M
		   INNER JOIN CAFE61.MEDIO_PAGO AS MP
		on M.MEDIO_PAGO_NRO_TARJETA = MP.MEDIO_PAGO_NRO_TARJETA
		   WHERE PEDIDO_NRO IS NOT NULL
		   GROUP BY PEDIDO_NRO,
		   PEDIDO_FECHA,
		   PEDIDO_TOTAL_CUPONES,
		   PEDIDO_TOTAL_PRODUCTOS,
		   PEDIDO_TARIFA_SERVICIO,
		   PEDIDO_TOTAL_SERVICIO,
		   PEDIDO_OBSERV,
		   PEDIDO_CALIFICACION,
		  MEDIO_PAGO_CODIGO) AS M
on PED.PEDIDO_NUMERO = M.PEDIDO_NRO
when matched then
UPDATE SET 
PEDIDO_MEDIO_PAGO = MEDIO_PAGO_CODIGO;
-- SE ACTUALIZA EL PEDIDO ESTADO
MERGE cafe61.PEDIDO As PED
USING (SELECT PEDIDO_NRO,
		   PEDIDO_FECHA,
		   PEDIDO_TOTAL_CUPONES,
		   PEDIDO_TOTAL_PRODUCTOS,
		   PEDIDO_TARIFA_SERVICIO,
		   PEDIDO_TOTAL_SERVICIO,
		   PEDIDO_OBSERV,
		   PEDIDO_CALIFICACION,
		   PEDIDO_ESTADO_CODIGO
		   FROM gd_esquema.Maestra AS M
		   INNER JOIN CAFE61.PEDIDO_ESTADO AS PE
		   on M.PEDIDO_ESTADO = PE.PEDIDO_ESTADO
		   WHERE PEDIDO_NRO IS NOT NULL
		   GROUP BY PEDIDO_NRO,
		   PEDIDO_FECHA,
		   PEDIDO_TOTAL_CUPONES,
		   PEDIDO_TOTAL_PRODUCTOS,
		   PEDIDO_TARIFA_SERVICIO,
		   PEDIDO_TOTAL_SERVICIO,
		   PEDIDO_OBSERV,
		   PEDIDO_CALIFICACION,
		  PEDIDO_ESTADO_CODIGO) AS M
on PED.PEDIDO_NUMERO = M.PEDIDO_NRO
when matched then
UPDATE SET 
PEDIDO_ESTADO = PEDIDO_ESTADO_CODIGO;
		-- Añadir una columna de identidad como clave primaria
		ALTER TABLE CAFE61.PEDIDO
		ADD CONSTRAINT PK_PEDIDO_NUMERO
		PRIMARY KEY (PEDIDO_NUMERO)

		-- Agregar la clave foránea a la columna OperadorReclamo
		ALTER TABLE CAFE61.PEDIDO
		ADD CONSTRAINT FK_PEDIDO_USUARIO
		FOREIGN KEY (PEDIDO_USUARIO)
		REFERENCES CAFE61.USUARIO (USUARIO_CODIGO);
		
		ALTER TABLE CAFE61.PEDIDO
		ADD CONSTRAINT FK_PEDIDO_MEDIO_PAGO
		FOREIGN KEY (PEDIDO_MEDIO_PAGO)
		REFERENCES CAFE61.MEDIO_PAGO (MEDIO_PAGO_CODIGO);

		ALTER TABLE CAFE61.PEDIDO
		ADD CONSTRAINT FK_PEDIDO_ENVIO_PEDIDO
		FOREIGN KEY (PEDIDO_ENVIO_PEDIDO)
		REFERENCES CAFE61.ENVIO_PEDIDO (ENVIO_PEDIDO_CODIGO);

		ALTER TABLE CAFE61.PEDIDO
		ADD CONSTRAINT FK_PEDIDO_LOCAL
		FOREIGN KEY (PEDIDO_LOCAL)
		REFERENCES CAFE61.LOCAL (LOCAL_CODIGO);

		ALTER TABLE CAFE61.PEDIDO
		ADD CONSTRAINT FK_PEDIDO_ESTADO
		FOREIGN KEY (PEDIDO_ESTADO)
		REFERENCES CAFE61.PEDIDO_ESTADO (PEDIDO_ESTADO_CODIGO);
GO
--Reclamo
create procedure cafe61.reclamo_crear
as
CREATE TABLE CAFE61.RECLAMO(
		   RECLAMO_NUMERO decimal(18,0) NOT NULL,
           RECLAMO_DESCRIPCION nvarchar(255),
           RECLAMO_FECHA datetime,
           RECLAMO_SOLUCION nvarchar(255),
           RECLAMO_FECHA_SOLUCION datetime,
           RECLAMO_CALIFICACION decimal(18,2),
	       RECLAMO_OPERADOR int,
	       RECLAMO_ESTADO int,
		   RECLAMO_PEDIDO_NUMERO decimal(18,0),
		   RECLAMO_TIPO int,
		   )
	INSERT INTO CAFE61.RECLAMO
	SELECT RECLAMO_NRO,
		   RECLAMO_DESCRIPCION,
		   RECLAMO_FECHA,
		   RECLAMO_SOLUCION,
		   RECLAMO_FECHA_SOLUCION,
		   RECLAMO_CALIFICACION,
		   O.OPERADOR_CODIGO,
		   E.RECLAMO_ESTADO_CODIGO,
		   P.PEDIDO_NUMERO,
		   T.TIPO_RECLAMO_CODIGO
	FROM gd_esquema.Maestra as M
		INNER JOIN CAFE61.OPERADOR_RECLAMO AS O
		on M.OPERADOR_RECLAMO_APELLIDO = O.OPERADOR_RECLAMO_APELLIDO AND M.OPERADOR_RECLAMO_DNI = O.OPERADOR_RECLAMO_DNI AND M.OPERADOR_RECLAMO_NOMBRE = O.OPERADOR_RECLAMO_NOMBRE
		INNER JOIN CAFE61.RECLAMO_ESTADO as E
		on M.RECLAMO_ESTADO = E.RECLAMO_ESTADO
		INNER JOIN CAFE61.PEDIDO as P
		on M.PEDIDO_NRO = P.PEDIDO_NUMERO		
		INNER JOIN CAFE61.TIPO_RECLAMO as T
		on M.RECLAMO_TIPO = T.TIPO_RECLAMO_DESCRIPCION
		where M.OPERADOR_RECLAMO_DNI IS NOT NULL AND M.OPERADOR_RECLAMO_NOMBRE IS NOT NULL AND M.OPERADOR_RECLAMO_APELLIDO IS NOT NULL AND M.RECLAMO_TIPO IS NOT NULL AND M.PEDIDO_NRO IS NOT NULL AND M.RECLAMO_ESTADO IS NOT NULL
	GROUP BY RECLAMO_NRO,
		   RECLAMO_DESCRIPCION,
		   RECLAMO_FECHA,
		   RECLAMO_SOLUCION,
		   RECLAMO_FECHA_SOLUCION,
		   RECLAMO_CALIFICACION,
		   O.OPERADOR_CODIGO,
		   E.RECLAMO_ESTADO_CODIGO,
		   P.PEDIDO_NUMERO,
		   T.TIPO_RECLAMO_CODIGO
		-- Añadir una columna de identidad como clave primaria
		ALTER TABLE CAFE61.RECLAMO
		ADD CONSTRAINT PK_RECLAMO_NUMERO
		PRIMARY KEY (RECLAMO_NUMERO)
		-- Agregar la clave foránea a la columna OperadorReclamo
		ALTER TABLE CAFE61.RECLAMO
		ADD CONSTRAINT FK_RECLAMO_OPERADOR
		FOREIGN KEY (RECLAMO_OPERADOR)
		REFERENCES CAFE61.OPERADOR_RECLAMO (OPERADOR_CODIGO);
GO
-- Cupon
create procedure cafe61.cupon_crear
as
CREATE TABLE CAFE61.CUPON(
           CUPON_NUMERO decimal(18,0) NOT NULL,
           CUPON_MONTO decimal(18,2),
           CUPON_FECHA_ALTA datetime,
		   CUPON_FECHA_VENCIMIENTO datetime,
	       CUPON_USUARIO int
		   )
	INSERT INTO CAFE61.CUPON
	SELECT CUPON_NRO,
		   CUPON_MONTO,
		   CUPON_FECHA_ALTA,
		   CUPON_FECHA_VENCIMIENTO,
		   U.USUARIO_CODIGO
	FROM gd_esquema.Maestra as M
		INNER JOIN CAFE61.USUARIO AS U
		on M.USUARIO_DNI = U.USUARIO_DNI AND M.USUARIO_NOMBRE = U.USUARIO_NOMBRE AND M.USUARIO_APELLIDO = U.USUARIO_APELLIDO
		where M.USUARIO_DNI IS NOT NULL AND M.USUARIO_NOMBRE IS NOT NULL AND M.USUARIO_APELLIDO IS NOT NULL AND M.MARCA_TARJETA IS NOT NULL AND M.MEDIO_PAGO_TIPO IS NOT NULL AND M.CUPON_NRO IS NOT NULL
	GROUP BY CUPON_NRO,
		   CUPON_MONTO,
		   CUPON_FECHA_ALTA,
		   CUPON_FECHA_VENCIMIENTO,
		   U.USUARIO_CODIGO

		-- Agrego clave primaria
		ALTER TABLE CAFE61.CUPON
		ADD CONSTRAINT PK_CUPON_NUMERO
		PRIMARY KEY (CUPON_NUMERO)

		-- Agregar la clave foránea a la columna OperadorReclamo
		ALTER TABLE CAFE61.CUPON
		ADD CONSTRAINT FK_CUPON_USUARIO
		FOREIGN KEY (CUPON_USUARIO)
		REFERENCES CAFE61.USUARIO (USUARIO_CODIGO);
go
-- Cupon Reclamo
create procedure cafe61.cupon_reclamo_crear
as
CREATE TABLE CAFE61.CUPON_RECLAMO(
		   CUPON_RECLAMO_CUPON decimal(18,0) NOT NULL,
           CUPON_RECLAMO_RECLAMO decimal(18,0) NOT NULL,
		   )
	INSERT INTO CAFE61.CUPON_RECLAMO
	SELECT C.CUPON_NUMERO,
		   R.RECLAMO_NUMERO
	FROM gd_esquema.Maestra as M
		INNER JOIN CAFE61.CUPON AS C
		on M.CUPON_NRO = C.CUPON_NUMERO
		INNER JOIN CAFE61.RECLAMO AS R
		on M.RECLAMO_NRO = R.RECLAMO_NUMERO 
		where M.CUPON_NRO IS NOT NULL AND M.RECLAMO_NRO IS NOT NULL 
	GROUP BY C.CUPON_NUMERO,
		   R.RECLAMO_NUMERO

		-- Agregar la clave foránea a la columna CUPON NUMERO
		ALTER TABLE CAFE61.CUPON_RECLAMO
		ADD CONSTRAINT FK_CUPON_RECLAMO_CUPON
		FOREIGN KEY (CUPON_RECLAMO_CUPON)
		REFERENCES CAFE61.CUPON (CUPON_NUMERO);
		-- Agregar la clave foránea a la columna RECLAMO NUMERO
		ALTER TABLE CAFE61.CUPON_RECLAMO
		ADD CONSTRAINT FK_CUPON_RECLAMO_RECLAMO
		FOREIGN KEY (CUPON_RECLAMO_RECLAMO)
		REFERENCES CAFE61.RECLAMO (RECLAMO_NUMERO);
go
-- Cupon Pedido
create procedure cafe61.cupon_pedido_crear
as
CREATE TABLE CAFE61.CUPON_PEDIDO(
		   CUPON_PEDIDO_CUPON decimal(18,0),
           CUPON_PEDIDO_PEDIDO decimal(18,0)
		   )
	INSERT INTO CAFE61.CUPON_PEDIDO
	SELECT C.CUPON_NUMERO,
		   P.PEDIDO_NUMERO
	FROM gd_esquema.Maestra as M
		INNER JOIN CAFE61.CUPON AS C
		on M.CUPON_NRO = C.CUPON_NUMERO
		INNER JOIN CAFE61.PEDIDO AS P
		on M.RECLAMO_NRO = P.PEDIDO_NUMERO 
		where M.CUPON_NRO IS NOT NULL AND M.PEDIDO_NRO IS NOT NULL
	GROUP BY C.CUPON_NUMERO,
		   P.PEDIDO_NUMERO

		-- Agregar la clave foránea a la columna CUPON NUMERO
		ALTER TABLE CAFE61.CUPON_PEDIDO
		ADD CONSTRAINT FK_CUPON_PEDIDO_CUPON
		FOREIGN KEY (CUPON_PEDIDO_CUPON)
		REFERENCES CAFE61.CUPON (CUPON_NUMERO);
		-- Agregar la clave foránea a la columna PEDIDO NUMERO
		ALTER TABLE CAFE61.CUPON_PEDIDO
		ADD CONSTRAINT FK_CUPON_PEDIDO_PEDIDO
		FOREIGN KEY (CUPON_PEDIDO_PEDIDO)
		REFERENCES CAFE61.PEDIDO (PEDIDO_NUMERO);
go
-- PRODUCTO LOCAL
create procedure cafe61.producto_local_crear
as
CREATE TABLE CAFE61.PRODUCTO_LOCAL(
           PRODUCTO_LOCAL_PRECIO decimal(18,2),
           PRODUCTO_LOCAL_LOCAL int,
		   PRODUCTO_LOCAL_PRODUCTO nvarchar(50) NOT NULL
		   )
	INSERT INTO CAFE61.PRODUCTO_LOCAL
	SELECT M.PRODUCTO_LOCAL_PRECIO,
		   L.LOCAL_CODIGO,
		   M.PRODUCTO_LOCAL_CODIGO
	FROM gd_esquema.Maestra as M
		INNER JOIN CAFE61.LOCAL AS L
		on M.LOCAL_NOMBRE= L.LOCAL_NOMBRE AND M.LOCAL_DESCRIPCION = L.LOCAL_DESCRIPCION
	WHERE M.PRODUCTO_LOCAL_CODIGO IS NOT NULL
	GROUP BY M.PRODUCTO_LOCAL_PRECIO,
		   L.LOCAL_CODIGO,
		   M.PRODUCTO_LOCAL_CODIGO
 
		-- Añadir una columna de identidad como clave primaria
		ALTER TABLE CAFE61.PRODUCTO_LOCAL
		ADD PRODUCTO_LOCAL_CODIGO INT IDENTITY(1,1) PRIMARY KEY;

		-- Agregar la clave foránea a la columna OperadorReclamo
		ALTER TABLE CAFE61.PRODUCTO_LOCAL
		ADD CONSTRAINT FK_PRODUCTO_LOCAL_PRODUCTO
		FOREIGN KEY (PRODUCTO_LOCAL_PRODUCTO)
		REFERENCES CAFE61.PRODUCTO (PRODUCTO_CODIGO);

		ALTER TABLE CAFE61.PRODUCTO_LOCAL
		ADD CONSTRAINT FK_PRODUCTO_LOCAL_LOCAL
		FOREIGN KEY (PRODUCTO_LOCAL_LOCAL)
		REFERENCES CAFE61.LOCAL (LOCAL_CODIGO);
go
-- PRODUCTO PEDIDO
create procedure cafe61.producto_pedido_crear
as
CREATE TABLE CAFE61.PRODUCTO_PEDIDO(
		   PRODUCTO_PEDIDO_PEDIDO decimal(18,0) NOT NULL,
           PRODUCTO_PEDIDO_CODIGO int NOT NULL,
		   PRODUCTO_PEDIDO_CANTIDAD decimal(18,0),
		   PRODUCTO_PEDIDO_PRECIO decimal(18,2)
		   )
	INSERT INTO CAFE61.PRODUCTO_PEDIDO
	SELECT P.PEDIDO_NUMERO,
		   PL.PRODUCTO_LOCAL_CODIGO,
		   SUM(M.PRODUCTO_CANTIDAD),
		   SUM(M.PRODUCTO_LOCAL_PRECIO)
	FROM gd_esquema.Maestra as M
		INNER JOIN CAFE61.PRODUCTO_LOCAL AS PL
		on M.PRODUCTO_LOCAL_CODIGO = PL.PRODUCTO_LOCAL_PRODUCTO
		INNER JOIN cafe61.LOCAL AS L
		ON M.LOCAL_NOMBRE = L.LOCAL_NOMBRE AND M.LOCAL_DESCRIPCION = L.LOCAL_DESCRIPCION AND L.LOCAL_CODIGO = PL.PRODUCTO_LOCAL_LOCAL
		INNER JOIN CAFE61.PEDIDO AS P
		on M.PEDIDO_NRO = P.PEDIDO_NUMERO
		where M.PRODUCTO_LOCAL_CODIGO IS NOT NULL AND M.PEDIDO_NRO IS NOT NULL AND M.PRODUCTO_LOCAL_CODIGO IS NOT NULL
	GROUP BY P.PEDIDO_NUMERO,
		   PL.PRODUCTO_LOCAL_CODIGO

		-- Añadir una columna de identidad como clave primaria
		ALTER TABLE CAFE61.PRODUCTO_PEDIDO
		ADD CONSTRAINT PK_PRODUCTO_PEDIDO
		PRIMARY KEY (PRODUCTO_PEDIDO_PEDIDO,PRODUCTO_PEDIDO_CODIGO)
		-- Agregar la clave foránea a la columna LOCALIDAD_CODIGO
		ALTER TABLE CAFE61.PRODUCTO_PEDIDO
		ADD CONSTRAINT FK_PRODUCTO_PEDIDO_PEDIDO
		FOREIGN KEY (PRODUCTO_PEDIDO_PEDIDO)
		REFERENCES CAFE61.PEDIDO (PEDIDO_NUMERO);
		-- Agregar la clave foránea a la columna REPARTIDOR CODIG
		ALTER TABLE CAFE61.PRODUCTO_PEDIDO
		ADD CONSTRAINT FK_PRODUCTO_PEDIDO_LOCAL_CODIGO
		FOREIGN KEY (PRODUCTO_PEDIDO_CODIGO)
		REFERENCES CAFE61.PRODUCTO_LOCAL (PRODUCTO_LOCAL_CODIGO);
go
-- PAQUETE
create procedure cafe61.paquete_crear
as
CREATE TABLE CAFE61.PAQUETE(
		   PAQUETE_TIPO int,
           PAQUETE_ALTO_MAX decimal(18,2),
		   PAQUETE_ANCHO_MAX decimal(18,2),
		   PAQUETE_LARGO_MAX decimal(18,2),
		   PAQUETE_PESO_MAX decimal(18,2)
		   )
	INSERT INTO CAFE61.PAQUETE
	SELECT P.PAQUETE_TIPO_CODIGO,
		   PAQUETE_ALTO_MAX,
		   PAQUETE_ANCHO_MAX,
		   PAQUETE_LARGO_MAX,
		   PAQUETE_PESO_MAX
	FROM gd_esquema.Maestra as M
		INNER JOIN CAFE61.PAQUETE_TIPO AS P
		on M.PAQUETE_TIPO = P.PAQUETE_TIPO
		where M.PAQUETE_TIPO IS NOT NULL
	GROUP BY P.PAQUETE_TIPO_CODIGO,
		   PAQUETE_ALTO_MAX,
		   PAQUETE_ANCHO_MAX,
		   PAQUETE_LARGO_MAX,
		   PAQUETE_PESO_MAX

		-- Añadir una columna de identidad como clave primaria
		ALTER TABLE CAFE61.PAQUETE
		ADD PAQUETE_CODIGO INT IDENTITY(1,1) PRIMARY KEY;

		-- Agregar la clave foránea a la columna OperadorReclamo
		ALTER TABLE CAFE61.PAQUETE
		ADD CONSTRAINT FK_PAQUETE_TIPO
		FOREIGN KEY (PAQUETE_TIPO)
		REFERENCES CAFE61.PAQUETE (PAQUETE_CODIGO);
go
-- ENVIO MENSAJERIA
create procedure cafe61.envio_mensajeria_crear
as
CREATE TABLE CAFE61.ENVIO_MENSAJERIA(
		   ENVIO_MENSAJERIA_NUMERO decimal(18,0) NOT NULL,
		   ENVIO_MENSAJERIA_PAQUETE int,
		   ENVIO_MENSAJERIA_RECORRIDO int,
		   ENVIO_MENSAJERIA_PRECIO_ENVIO decimal(18,2),
		   ENVIO_MENSAJERIA_PRECIO_SEGURO decimal(18,2),
		   ENVIO_MENSAJERIA_REPARTIDOR int,
		   ENVIO_MENSAJERIA_PROPINA decimal(18,2),
		   ENVIO_MENSAJERIA_MEDIO_PAGO int,
		   ENVIO_MENSAJERIA_TOTAL decimal(18,2),
		   ENVIO_MENSAJERIA_ESTADO int,
		   ENVIO_MENSAJERIA_FECHA_PEDIDO datetime,
		   ENVIO_MENSAJERIA_FECHA_ESTIMADO datetime,
		   ENVIO_MENSAJERIA_FECHA_ENTREGA datetime,
		   ENVIO_MENSAJERIA_CALIFICACION decimal(18,0),
		   ENVIO_MENSAJERIA_OBSERV nvarchar(255)
		   )
	INSERT INTO CAFE61.ENVIO_MENSAJERIA (ENVIO_MENSAJERIA_NUMERO,
	ENVIO_MENSAJERIA_PRECIO_ENVIO,
	ENVIO_MENSAJERIA_PRECIO_SEGURO,
	ENVIO_MENSAJERIA_PROPINA,
	ENVIO_MENSAJERIA_TOTAL,
	ENVIO_MENSAJERIA_FECHA_PEDIDO,
	ENVIO_MENSAJERIA_FECHA_ESTIMADO,
	ENVIO_MENSAJERIA_FECHA_ENTREGA,
	ENVIO_MENSAJERIA_CALIFICACION,
	ENVIO_MENSAJERIA_OBSERV)
	SELECT M.ENVIO_MENSAJERIA_NRO,
	M.ENVIO_MENSAJERIA_PRECIO_ENVIO,
	M.ENVIO_MENSAJERIA_PRECIO_SEGURO,
	M.ENVIO_MENSAJERIA_PROPINA,
	M.ENVIO_MENSAJERIA_TOTAL,
	M.ENVIO_MENSAJERIA_FECHA,
	M.ENVIO_MENSAJERIA_TIEMPO_ESTIMADO,
	M.ENVIO_MENSAJERIA_FECHA_ENTREGA,
	M.ENVIO_MENSAJERIA_CALIFICACION,
	M.ENVIO_MENSAJERIA_OBSERV
	FROM gd_esquema.Maestra as M
		where M.ENVIO_MENSAJERIA_NRO IS NOT NULL
	GROUP BY ENVIO_MENSAJERIA_NRO,
	M.ENVIO_MENSAJERIA_PRECIO_ENVIO,
	M.ENVIO_MENSAJERIA_PRECIO_SEGURO,
	M.ENVIO_MENSAJERIA_PROPINA,
	M.ENVIO_MENSAJERIA_TOTAL,
	M.ENVIO_MENSAJERIA_FECHA,
	M.ENVIO_MENSAJERIA_TIEMPO_ESTIMADO,
	M.ENVIO_MENSAJERIA_FECHA_ENTREGA,
	M.ENVIO_MENSAJERIA_CALIFICACION,
	M.ENVIO_MENSAJERIA_OBSERV
-- Se actualiza el paquete codigo
MERGE cafe61.ENVIO_MENSAJERIA As EM
USING (SELECT ENVIO_MENSAJERIA_NRO,
	M.ENVIO_MENSAJERIA_PRECIO_ENVIO,
	M.ENVIO_MENSAJERIA_PRECIO_SEGURO,
	M.ENVIO_MENSAJERIA_PROPINA,
	M.ENVIO_MENSAJERIA_TOTAL,
	M.ENVIO_MENSAJERIA_FECHA,
	M.ENVIO_MENSAJERIA_TIEMPO_ESTIMADO,
	M.ENVIO_MENSAJERIA_FECHA_ENTREGA,
	M.ENVIO_MENSAJERIA_CALIFICACION,
	M.ENVIO_MENSAJERIA_OBSERV,
	P.PAQUETE_CODIGO
	FROM gd_esquema.Maestra as M
	INNER JOIN CAFE61.PAQUETE_TIPO AS PT
	on M.PAQUETE_TIPO = PT.PAQUETE_TIPO
	INNER JOIN CAFE61.PAQUETE AS P
	on P.PAQUETE_TIPO = PT.PAQUETE_TIPO_CODIGO
	where M.ENVIO_MENSAJERIA_NRO IS NOT NULL and M.PAQUETE_TIPO IS NOT NULL
	GROUP BY ENVIO_MENSAJERIA_NRO,
	M.ENVIO_MENSAJERIA_PRECIO_ENVIO,
	M.ENVIO_MENSAJERIA_PRECIO_SEGURO,
	M.ENVIO_MENSAJERIA_PROPINA,
	M.ENVIO_MENSAJERIA_TOTAL,
	M.ENVIO_MENSAJERIA_FECHA,
	M.ENVIO_MENSAJERIA_TIEMPO_ESTIMADO,
	M.ENVIO_MENSAJERIA_FECHA_ENTREGA,
	M.ENVIO_MENSAJERIA_CALIFICACION,
	M.ENVIO_MENSAJERIA_OBSERV,
	P.PAQUETE_CODIGO) AS M
on EM.ENVIO_MENSAJERIA_NUMERO = M.ENVIO_MENSAJERIA_NRO
when matched then
UPDATE SET 
ENVIO_MENSAJERIA_PAQUETE = PAQUETE_CODIGO;
-- Se actualiza el codigo del recorrido
MERGE cafe61.ENVIO_MENSAJERIA As EM
USING (SELECT ENVIO_MENSAJERIA_NRO,
	M.ENVIO_MENSAJERIA_PRECIO_ENVIO,
	M.ENVIO_MENSAJERIA_PRECIO_SEGURO,
	M.ENVIO_MENSAJERIA_PROPINA,
	M.ENVIO_MENSAJERIA_TOTAL,
	M.ENVIO_MENSAJERIA_FECHA,
	M.ENVIO_MENSAJERIA_TIEMPO_ESTIMADO,
	M.ENVIO_MENSAJERIA_FECHA_ENTREGA,
	M.ENVIO_MENSAJERIA_CALIFICACION,
	M.ENVIO_MENSAJERIA_OBSERV,
	ER.ENVIO_RECORRIDO_CODIGO
	FROM gd_esquema.Maestra as M
	INNER JOIN CAFE61.ENVIO_RECORRIDO AS ER
	on M.ENVIO_MENSAJERIA_DIR_ORIG = ER.ENVIO_RECORRIDO_DIR_ORIG AND M.ENVIO_MENSAJERIA_DIR_DEST = ER.ENVIO_RECORRIDO_DIR_DEST AND M.ENVIO_MENSAJERIA_KM = ER.ENVIO_RECORRIDO_KM
	where M.ENVIO_MENSAJERIA_NRO IS NOT NULL and M.ENVIO_MENSAJERIA_DIR_ORIG IS NOT NULL and M.ENVIO_MENSAJERIA_DIR_DEST IS NOT NULL and M.ENVIO_MENSAJERIA_KM IS NOT NULL
	GROUP BY ENVIO_MENSAJERIA_NRO,
	M.ENVIO_MENSAJERIA_PRECIO_ENVIO,
	M.ENVIO_MENSAJERIA_PRECIO_SEGURO,
	M.ENVIO_MENSAJERIA_PROPINA,
	M.ENVIO_MENSAJERIA_TOTAL,
	M.ENVIO_MENSAJERIA_FECHA,
	M.ENVIO_MENSAJERIA_TIEMPO_ESTIMADO,
	M.ENVIO_MENSAJERIA_FECHA_ENTREGA,
	M.ENVIO_MENSAJERIA_CALIFICACION,
	M.ENVIO_MENSAJERIA_OBSERV,
	ER.ENVIO_RECORRIDO_CODIGO) AS M
on EM.ENVIO_MENSAJERIA_NUMERO = M.ENVIO_MENSAJERIA_NRO
when matched then
UPDATE SET 
ENVIO_MENSAJERIA_RECORRIDO = ENVIO_RECORRIDO_CODIGO;
-- Se actualiza el codigo del repartidor
MERGE cafe61.ENVIO_MENSAJERIA As EM
USING (SELECT ENVIO_MENSAJERIA_NRO,
	M.ENVIO_MENSAJERIA_PRECIO_ENVIO,
	M.ENVIO_MENSAJERIA_PRECIO_SEGURO,
	M.ENVIO_MENSAJERIA_PROPINA,
	M.ENVIO_MENSAJERIA_TOTAL,
	M.ENVIO_MENSAJERIA_FECHA,
	M.ENVIO_MENSAJERIA_TIEMPO_ESTIMADO,
	M.ENVIO_MENSAJERIA_FECHA_ENTREGA,
	M.ENVIO_MENSAJERIA_CALIFICACION,
	M.ENVIO_MENSAJERIA_OBSERV,
	R.REPARTIDOR_CODIGO
	FROM gd_esquema.Maestra as M
	INNER JOIN CAFE61.REPARTIDOR AS R
	on M.REPARTIDOR_APELLIDO = R.REPARTIDOR_APELLIDO AND M.REPARTIDOR_DNI = R.REPARTIDOR_DNI AND M.REPARTIDOR_NOMBRE = R.REPARTIDOR_NOMBRE
	where M.ENVIO_MENSAJERIA_NRO IS NOT NULL and M.REPARTIDOR_APELLIDO IS NOT NULL and M.REPARTIDOR_DNI IS NOT NULL and M.REPARTIDOR_NOMBRE IS NOT NULL
	GROUP BY ENVIO_MENSAJERIA_NRO,
	M.ENVIO_MENSAJERIA_PRECIO_ENVIO,
	M.ENVIO_MENSAJERIA_PRECIO_SEGURO,
	M.ENVIO_MENSAJERIA_PROPINA,
	M.ENVIO_MENSAJERIA_TOTAL,
	M.ENVIO_MENSAJERIA_FECHA,
	M.ENVIO_MENSAJERIA_TIEMPO_ESTIMADO,
	M.ENVIO_MENSAJERIA_FECHA_ENTREGA,
	M.ENVIO_MENSAJERIA_CALIFICACION,
	M.ENVIO_MENSAJERIA_OBSERV,
	R.REPARTIDOR_CODIGO) AS M
on EM.ENVIO_MENSAJERIA_NUMERO = M.ENVIO_MENSAJERIA_NRO
when matched then
UPDATE SET 
ENVIO_MENSAJERIA_REPARTIDOR = REPARTIDOR_CODIGO;
-- Se actualiza el codigo del medio de pago
MERGE cafe61.ENVIO_MENSAJERIA As EM
USING (SELECT ENVIO_MENSAJERIA_NRO,
	M.ENVIO_MENSAJERIA_PRECIO_ENVIO,
	M.ENVIO_MENSAJERIA_PRECIO_SEGURO,
	M.ENVIO_MENSAJERIA_PROPINA,
	M.ENVIO_MENSAJERIA_TOTAL,
	M.ENVIO_MENSAJERIA_FECHA,
	M.ENVIO_MENSAJERIA_TIEMPO_ESTIMADO,
	M.ENVIO_MENSAJERIA_FECHA_ENTREGA,
	M.ENVIO_MENSAJERIA_CALIFICACION,
	M.ENVIO_MENSAJERIA_OBSERV,
	MP.MEDIO_PAGO_CODIGO
	FROM gd_esquema.Maestra as M
	INNER JOIN CAFE61.MEDIO_PAGO AS MP
	on M.MEDIO_PAGO_NRO_TARJETA = MP.MEDIO_PAGO_NRO_TARJETA
	where M.ENVIO_MENSAJERIA_NRO IS NOT NULL and M.MEDIO_PAGO_NRO_TARJETA IS NOT NULL
	GROUP BY ENVIO_MENSAJERIA_NRO,
	M.ENVIO_MENSAJERIA_PRECIO_ENVIO,
	M.ENVIO_MENSAJERIA_PRECIO_SEGURO,
	M.ENVIO_MENSAJERIA_PROPINA,
	M.ENVIO_MENSAJERIA_TOTAL,
	M.ENVIO_MENSAJERIA_FECHA,
	M.ENVIO_MENSAJERIA_TIEMPO_ESTIMADO,
	M.ENVIO_MENSAJERIA_FECHA_ENTREGA,
	M.ENVIO_MENSAJERIA_CALIFICACION,
	M.ENVIO_MENSAJERIA_OBSERV,
	MP.MEDIO_PAGO_CODIGO) AS M
on EM.ENVIO_MENSAJERIA_NUMERO = M.ENVIO_MENSAJERIA_NRO
when matched then
UPDATE SET 
ENVIO_MENSAJERIA_MEDIO_PAGO = MEDIO_PAGO_CODIGO;
-- Se actualiza el codigo del estado
MERGE cafe61.ENVIO_MENSAJERIA As EM
USING (SELECT ENVIO_MENSAJERIA_NRO,
	M.ENVIO_MENSAJERIA_PRECIO_ENVIO,
	M.ENVIO_MENSAJERIA_PRECIO_SEGURO,
	M.ENVIO_MENSAJERIA_PROPINA,
	M.ENVIO_MENSAJERIA_TOTAL,
	M.ENVIO_MENSAJERIA_FECHA,
	M.ENVIO_MENSAJERIA_TIEMPO_ESTIMADO,
	M.ENVIO_MENSAJERIA_FECHA_ENTREGA,
	M.ENVIO_MENSAJERIA_CALIFICACION,
	M.ENVIO_MENSAJERIA_OBSERV,
	E.ENVIO_MENSAJERIA_ESTADO_CODIGO
	FROM gd_esquema.Maestra as M
	INNER JOIN CAFE61.ENVIO_MENSAJERIA_ESTADO AS E
	on M.ENVIO_MENSAJERIA_ESTADO = E.ENVIO_MENSAJERIA_ESTADO
	where M.ENVIO_MENSAJERIA_NRO IS NOT NULL and M.MEDIO_PAGO_NRO_TARJETA IS NOT NULL
	GROUP BY ENVIO_MENSAJERIA_NRO,
	M.ENVIO_MENSAJERIA_PRECIO_ENVIO,
	M.ENVIO_MENSAJERIA_PRECIO_SEGURO,
	M.ENVIO_MENSAJERIA_PROPINA,
	M.ENVIO_MENSAJERIA_TOTAL,
	M.ENVIO_MENSAJERIA_FECHA,
	M.ENVIO_MENSAJERIA_TIEMPO_ESTIMADO,
	M.ENVIO_MENSAJERIA_FECHA_ENTREGA,
	M.ENVIO_MENSAJERIA_CALIFICACION,
	M.ENVIO_MENSAJERIA_OBSERV,
	E.ENVIO_MENSAJERIA_ESTADO_CODIGO) AS M
on EM.ENVIO_MENSAJERIA_NUMERO = M.ENVIO_MENSAJERIA_NRO
when matched then
UPDATE SET 
ENVIO_MENSAJERIA_ESTADO = ENVIO_MENSAJERIA_ESTADO_CODIGO;
		-- Añadir una columna de identidad como clave primaria
		ALTER TABLE CAFE61.ENVIO_MENSAJERIA
		ADD CONSTRAINT PK_ENVIO_MENSAJERIA_NUMERO
		PRIMARY KEY (ENVIO_MENSAJERIA_NUMERO)
		
		-- Agregar la clave foránea a la columna
		ALTER TABLE CAFE61.ENVIO_MENSAJERIA
		ADD CONSTRAINT FK_ENVIO_MENSAJERIA_ESTADO
		FOREIGN KEY (ENVIO_MENSAJERIA_ESTADO)
		REFERENCES CAFE61.ENVIO_MENSAJERIA_ESTADO (ENVIO_MENSAJERIA_ESTADO_CODIGO);

		ALTER TABLE CAFE61.ENVIO_MENSAJERIA
		ADD CONSTRAINT FK_ENVIO_MENSAJERIA_MEDIO_PAGO
		FOREIGN KEY (ENVIO_MENSAJERIA_MEDIO_PAGO)
		REFERENCES CAFE61.MEDIO_PAGO (MEDIO_PAGO_CODIGO);

		ALTER TABLE CAFE61.ENVIO_MENSAJERIA
		ADD CONSTRAINT FK_ENVIO_MENSAJERIA_REPARTIDOR
		FOREIGN KEY (ENVIO_MENSAJERIA_REPARTIDOR)
		REFERENCES CAFE61.REPARTIDOR (REPARTIDOR_CODIGO);

		ALTER TABLE CAFE61.ENVIO_MENSAJERIA
		ADD CONSTRAINT FK_ENVIO_MENSAJERIA_RECORRIDO
		FOREIGN KEY (ENVIO_MENSAJERIA_RECORRIDO)
		REFERENCES CAFE61.ENVIO_RECORRIDO (ENVIO_RECORRIDO_CODIGO);


		ALTER TABLE CAFE61.ENVIO_MENSAJERIA
		ADD CONSTRAINT FK_ENVIO_MENSAJERIA_PAQUETE
		FOREIGN KEY (ENVIO_MENSAJERIA_PAQUETE)
		REFERENCES CAFE61.PAQUETE (PAQUETE_CODIGO);
go
--Ejecucion de procedures
exec cafe61.LimpiezaEsquema
exec cafe61.operador_reclamo_crear
exec cafe61.reclamo_estado_crear
exec cafe61.tipo_reclamo_crear
exec cafe61.usuario_crear
exec cafe61.tipo_medio_pago_crear
exec cafe61.marca_tarjeta_crear
exec cafe61.envio_mensajeria_estado_crear
exec cafe61.paquete_tipo_crear
exec cafe61.envio_recorrido_crear
exec cafe61.provincia_crear
exec cafe61.tipo_movilidad_crear
exec cafe61.producto_crear
exec cafe61.local_tipo_crear
exec cafe61.pedido_estado_crear
exec cafe61.localidad_crear
exec cafe61.repartidor_crear
exec cafe61.repartidor_localidad_crear
exec cafe61.direccion_usuario_crear
exec cafe61.local_categoria_crear
exec cafe61.local_crear
exec cafe61.envio_pedido_crear
exec cafe61.medio_pago_crear
exec cafe61.pedido_crear
exec cafe61.reclamo_crear
exec cafe61.cupon_crear
exec cafe61.cupon_reclamo_crear
exec cafe61.cupon_pedido_crear
exec cafe61.producto_local_crear
exec cafe61.producto_pedido_crear
exec cafe61.paquete_crear
exec cafe61.envio_mensajeria_crear
