--Procedure para limpiar todas las tablas
create PROCEDURE cafe61.BI_LimpiezaEsquema
AS
	IF OBJECT_ID(N'cafe61.BI_ENVIO_MENSAJERIA', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_ENVIO_MENSAJERIA;  
	IF OBJECT_ID(N'cafe61.BI_PAQUETE', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_PAQUETE;  
	IF OBJECT_ID(N'cafe61.BI_PRODUCTO_PEDIDO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_PRODUCTO_PEDIDO;  
	IF OBJECT_ID(N'cafe61.BI_PRODUCTO_LOCAL', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_PRODUCTO_LOCAL;  
	IF OBJECT_ID(N'cafe61.BI_CUPON_PEDIDO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_CUPON_PEDIDO;  
	IF OBJECT_ID(N'cafe61.BI_CUPON_RECLAMO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_CUPON_RECLAMO;  
	IF OBJECT_ID(N'cafe61.BI_CUPON', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_CUPON;  
	IF OBJECT_ID(N'cafe61.BI_RECLAMO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_RECLAMO;  
	IF OBJECT_ID(N'cafe61.BI_PEDIDO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_PEDIDO;  
	IF OBJECT_ID(N'cafe61.BI_MEDIO_PAGO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_MEDIO_PAGO;  
	IF OBJECT_ID(N'cafe61.BI_MEDIO_PAGO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_MEDIO_PAGO;  
	IF OBJECT_ID(N'cafe61.BI_ENVIO_PEDIDO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_ENVIO_PEDIDO;  
	IF OBJECT_ID(N'cafe61.BI_LOCAL', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_LOCAL;  
	IF OBJECT_ID(N'cafe61.BI_LOCAL_CATEGORIA', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_LOCAL_CATEGORIA;  
	IF OBJECT_ID(N'cafe61.BI_REPARTIDOR_LOCALIDAD', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_REPARTIDOR_LOCALIDAD;  
	IF OBJECT_ID(N'cafe61.BI_REPARTIDOR', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_REPARTIDOR;  
	IF OBJECT_ID(N'cafe61.BI_LOCALIDAD', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_LOCALIDAD;  
	IF OBJECT_ID(N'cafe61.BI_PROVINCIA', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_PROVINCIA;  
	IF OBJECT_ID(N'cafe61.BI_ESTADO_PEDIDO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_ESTADO_PEDIDO;  
	IF OBJECT_ID(N'cafe61.BI_LOCAL_TIPO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_LOCAL_TIPO;  
	IF OBJECT_ID(N'cafe61.BI_PRODUCTO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_PRODUCTO;  
	IF OBJECT_ID(N'cafe61.BI_TIPO_MOVILIDAD', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_TIPO_MOVILIDAD;  
	IF OBJECT_ID(N'cafe61.BI_ENVIO_RECORRIDO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_ENVIO_RECORRIDO;  
	IF OBJECT_ID(N'cafe61.BI_TIPO_PAQUETE', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_TIPO_PAQUETE;  
	IF OBJECT_ID(N'cafe61.BI_ENVIO_MENSAJERIA_ESTADO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_ENVIO_MENSAJERIA_ESTADO;  
	IF OBJECT_ID(N'cafe61.BI_MARCA_TARJETA', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_MARCA_TARJETA;  
	IF OBJECT_ID(N'cafe61.BI_TIPO_MEDIO_PAGO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_TIPO_MEDIO_PAGO;  
	IF OBJECT_ID(N'cafe61.BI_DIRECCION_USUARIO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_DIRECCION_USUARIO;  
	IF OBJECT_ID(N'cafe61.BI_USUARIO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_USUARIO;  
	IF OBJECT_ID(N'cafe61.BI_TIPO_RECLAMO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_TIPO_RECLAMO;  
	IF OBJECT_ID(N'cafe61.BI_RECLAMO_ESTADO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_RECLAMO_ESTADO;  
	IF OBJECT_ID(N'cafe61.BI_OPERADOR_RECLAMO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_OPERADOR_RECLAMO;
	IF OBJECT_ID(N'cafe61.BI_RANGOETARIO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_RANGOETARIO;
	IF OBJECT_ID(N'cafe61.BI_TIEMPO', N'U') IS NOT NULL  
	   DROP TABLE cafe61.BI_TIEMPO;
go
-- Dimension PROVINCIA
CREATE PROCEDURE cafe61.BI_PROVINCIA_CREAR
AS
SELECT * 
INTO cafe61.BI_PROVINCIA
FROM cafe61.PROVINCIA

ALTER TABLE CAFE61.BI_PROVINCIA
ADD CONSTRAINT PK_PROVINCIA_CODIGO
PRIMARY KEY (PROVINCIA_CODIGO); 

GO
-- Dimension LOCALIDAD
CREATE PROCEDURE cafe61.BI_LOCALIDAD_CREAR
AS
SELECT * 
INTO cafe61.BI_LOCALIDAD
FROM cafe61.LOCALIDAD

ALTER TABLE CAFE61.BI_LOCALIDAD
ADD CONSTRAINT PK_LOCALIDAD_CODIGO
PRIMARY KEY (LOCALIDAD_CODIGO);

ALTER TABLE CAFE61.BI_LOCALIDAD
ADD CONSTRAINT FK_BI_LOCALIDAD_PROVINCIA
FOREIGN KEY (LOCALIDAD_PROVINCIA) REFERENCES CAFE61.BI_PROVINCIA

GO
-- Dimension TIPO MEDIO PAGO
CREATE PROCEDURE cafe61.BI_TIPO_MEDIO_PAGO_CREAR
AS
SELECT * 
INTO cafe61.BI_TIPO_MEDIO_PAGO 
FROM cafe61.TIPO_MEDIO_PAGO

ALTER TABLE CAFE61.BI_TIPO_MEDIO_PAGO
ADD CONSTRAINT PK_TIPO_MEDIO_PAGO_CODIGO
PRIMARY KEY (TIPO_MEDIO_PAGO_CODIGO); 
GO
-- Dimension TIPO LOCAL
CREATE PROCEDURE cafe61.BI_LOCAL_TIPO_CREAR
AS
SELECT * 
INTO cafe61.BI_LOCAL_TIPO
FROM cafe61.LOCAL_TIPO

ALTER TABLE CAFE61.BI_LOCAL_TIPO
ADD CONSTRAINT PK_LOCAL_TIPO_CODIGO
PRIMARY KEY (LOCAL_TIPO_CODIGO);
GO
-- Dimension LOCAL
CREATE PROCEDURE cafe61.BI_LOCAL_CREAR
AS
SELECT * 
INTO cafe61.BI_LOCAL
FROM cafe61.LOCAL

ALTER TABLE CAFE61.BI_LOCAL
ADD CONSTRAINT PK_LOCAL_CODIGO
PRIMARY KEY (LOCAL_CODIGO);

ALTER TABLE CAFE61.BI_LOCAL
ADD CONSTRAINT FK_BI_LOCAL_TIPO
FOREIGN KEY (LOCAL_TIPO) REFERENCES CAFE61.BI_LOCAL_TIPO

GO
-- Dimension TIPO MOVILIDAD
CREATE PROCEDURE cafe61.BI_TIPO_MOVILIDAD_CREAR
AS
SELECT * 
INTO cafe61.BI_TIPO_MOVILIDAD
FROM cafe61.TIPO_MOVILIDAD

ALTER TABLE CAFE61.BI_TIPO_MOVILIDAD
ADD CONSTRAINT PK_TIPO_MOVILIDAD_CODIGO
PRIMARY KEY (TIPO_MOVILIDAD_CODIGO)

GO
-- Dimension TIPO PAQUETE
CREATE PROCEDURE cafe61.BI_TIPO_PAQUETE_CREAR
AS
SELECT * 
INTO cafe61.BI_TIPO_PAQUETE
FROM cafe61.PAQUETE_TIPO

ALTER TABLE CAFE61.BI_TIPO_PAQUETE
ADD CONSTRAINT PK_BI_TIPO_PAQUETE_CODIGO
PRIMARY KEY (PAQUETE_TIPO_CODIGO);
GO
-- Dimension PAQUETE
CREATE PROCEDURE cafe61.BI_PAQUETE_CREAR
AS
SELECT * 
INTO cafe61.BI_PAQUETE
FROM cafe61.PAQUETE

ALTER TABLE CAFE61.BI_PAQUETE
ADD CONSTRAINT PK_BI_PAQUETE_CODIGO
PRIMARY KEY (PAQUETE_CODIGO)

ALTER TABLE CAFE61.BI_PAQUETE
ADD CONSTRAINT FK_BI_PAQUETE_TIPO
FOREIGN KEY (PAQUETE_TIPO) REFERENCES CAFE61.BI_TIPO_PAQUETE (PAQUETE_TIPO_CODIGO) 

GO
-- Dimension ESTADO PEDIDOS
CREATE PROCEDURE cafe61.BI_ESTADO_PEDIDO_CREAR
AS
SELECT * 
INTO cafe61.BI_ESTADO_PEDIDO
FROM cafe61.PEDIDO_ESTADO

ALTER TABLE CAFE61.BI_ESTADO_PEDIDO
ADD CONSTRAINT PK_ESTADO_PEDIDO_CODIGO
PRIMARY KEY (PEDIDO_ESTADO_CODIGO);
GO
-- Dimension ESTADO ENVIOS MENSAJERIA
CREATE PROCEDURE cafe61.BI_ENVIO_MENSAJERIA_ESTADO_CREAR
AS
SELECT * 
INTO cafe61.BI_ENVIO_MENSAJERIA_ESTADO
FROM cafe61.ENVIO_MENSAJERIA_ESTADO
GO
-- Dimension ESTADO RECLAMOS
CREATE PROCEDURE cafe61.BI_RECLAMO_ESTADO_CREAR
AS
SELECT * 
INTO cafe61.BI_RECLAMO_ESTADO
FROM cafe61.RECLAMO_ESTADO
GO
-- Dimension TIPO RECLAMOS
CREATE PROCEDURE cafe61.BI_TIPO_RECLAMO_CREAR
AS
SELECT * 
INTO cafe61.BI_TIPO_RECLAMO
FROM cafe61.TIPO_RECLAMO

ALTER TABLE CAFE61.BI_TIPO_RECLAMO
ADD CONSTRAINT PK_BI_TIPO_RECLAMO_CODIGO
PRIMARY KEY (TIPO_RECLAMO_CODIGO);
GO
-- Dimension TIEMPO
CREATE PROCEDURE cafe61.BI_TIEMPO_CREAR
AS
SELECT DISTINCT tiempo_anio,tiempo_mes,tiempo_dia,tiempo_franjahoraria
INTO cafe61.BI_TIEMPO
FROM (
    SELECT YEAR(PEDIDO_FECHA) AS tiempo_anio, MONTH(PEDIDO_FECHA) AS tiempo_mes,DATEPART(WEEKDAY, PEDIDO_FECHA) as tiempo_dia,CONCAT(RIGHT('00' + CAST(DATEPART(HOUR, PEDIDO_FECHA) AS VARCHAR(2)), 2), ':00 - ', RIGHT('00' + CAST(DATEPART(HOUR, PEDIDO_FECHA) + 2 AS VARCHAR(2)), 2), ':00') AS tiempo_franjahoraria
    FROM CAFE61.PEDIDO
    UNION
    SELECT YEAR(RECLAMO_FECHA) AS tiempo_anio, MONTH(RECLAMO_FECHA) AS tiempo_mes,DATEPART(WEEKDAY, RECLAMO_FECHA) as tiempo_dia,CONCAT(RIGHT('00' + CAST(DATEPART(HOUR, RECLAMO_FECHA) AS VARCHAR(2)), 2), ':00 - ', RIGHT('00' + CAST(DATEPART(HOUR, RECLAMO_FECHA) + 2 AS VARCHAR(2)), 2), ':00') AS tiempo_franjahoraria
    FROM CAFE61.RECLAMO
	UNION
    SELECT YEAR(ENVIO_MENSAJERIA_FECHA_PEDIDO) AS tiempo_anio, MONTH(ENVIO_MENSAJERIA_FECHA_PEDIDO) AS tiempo_mes,DATEPART(WEEKDAY, ENVIO_MENSAJERIA_FECHA_PEDIDO) as tiempo_dia,CONCAT(RIGHT('00' + CAST(DATEPART(HOUR, ENVIO_MENSAJERIA_FECHA_PEDIDO) AS VARCHAR(2)), 2), ':00 - ', RIGHT('00' + CAST(DATEPART(HOUR, ENVIO_MENSAJERIA_FECHA_PEDIDO) + 2 AS VARCHAR(2)), 2), ':00') AS tiempo_franjahoraria
    FROM CAFE61.ENVIO_MENSAJERIA 
	)AS dimension;
	ALTER TABLE cafe61.BI_TIEMPO
ADD tiempo_codigo int primary key identity(1,1)
GO
--Dimension RANGO ETARIO
CREATE PROCEDURE CAFE61.BI_RANGOETARIO_CREAR
AS
CREATE TABLE CAFE61.BI_RANGOETARIO (
    RANGOETARIO_CODIGO INT PRIMARY KEY,
    RANGOETARIO_DESDE INT,
    RANGOETARIO_HASTA INT
);

INSERT INTO CAFE61.BI_RANGOETARIO (RANGOETARIO_CODIGO, RANGOETARIO_DESDE, RANGOETARIO_HASTA)
VALUES
    (1, 0, 24),
    (2, 25, 35),
    (3, 36, 55),
    (4, 56, 150);
GO
-- Dimension Repartidor
CREATE PROCEDURE CAFE61.BI_REPARTIDOR_CREAR
AS
SELECT * 
INTO CAFE61.BI_REPARTIDOR
FROM CAFE61.REPARTIDOR

--PK BI_REPARTIDOR
ALTER TABLE CAFE61.BI_REPARTIDOR
ADD CONSTRAINT PK_BI_REPARIDOR_CODIGO
PRIMARY KEY (REPARTIDOR_CODIGO);

-- FK a TIPO MOVILIDAD
ALTER TABLE CAFE61.BI_REPARTIDOR
ADD CONSTRAINT FK_BI_REPARTIDOR_TIPO_MOVILIDAD
FOREIGN KEY (REPARTIDOR_TIPO_MOVILIDAD) REFERENCES CAFE61.BI_TIPO_MOVILIDAD (TIPO_MOVILIDAD_CODIGO);

GO
--Dimension Envio Pedido
CREATE PROCEDURE CAFE61.BI_ENVIO_PEDIDO_CREAR
AS
SELECT * 
INTO CAFE61.BI_ENVIO_PEDIDO
FROM CAFE61.ENVIO_PEDIDO
--PK BI_ENVIO_PEDIDO
ALTER TABLE CAFE61.BI_ENVIO_PEDIDO
ADD CONSTRAINT PK_BI_ENVIO_PEDIDO_CODIGO
PRIMARY KEY (ENVIO_PEDIDO_CODIGO);
-- FK a Repartidor
ALTER TABLE CAFE61.BI_ENVIO_PEDIDO
ADD CONSTRAINT FK_BI_ENVIO_PEDIDO_REPARTIDOR
FOREIGN KEY (ENVIO_PEDIDO_REPARTIDOR) REFERENCES CAFE61.BI_REPARTIDOR (REPARTIDOR_CODIGO);
-- Col RangoEtarioRepartidor
ALTER TABLE CAFE61.BI_ENVIO_PEDIDO
ADD ENVIO_PEDIDO_RANGO_ETARIO_REPARTIDOR INT;
-- Agrego datos a Col RangoEtarioRepartidor
UPDATE CAFE61.BI_ENVIO_PEDIDO
SET ENVIO_PEDIDO_RANGO_ETARIO_REPARTIDOR = re.RANGOETARIO_CODIGO
FROM CAFE61.BI_ENVIO_PEDIDO e
	INNER JOIN CAFE61.REPARTIDOR r ON e.ENVIO_PEDIDO_REPARTIDOR = r.REPARTIDOR_CODIGO
	INNER JOIN CAFE61.BI_RANGOETARIO re ON DATEDIFF(year, r.REPARTIDOR_FECHA_NAC, GETDATE()) BETWEEN re.RANGOETARIO_DESDE AND re.RANGOETARIO_HASTA;
-- FK a RangoEtarioRepartidor
ALTER TABLE CAFE61.BI_ENVIO_PEDIDO
ADD CONSTRAINT FK_BI_ENVIO_PEDIDO_RANGO_ETARIO_REPARTIDOR
FOREIGN KEY (ENVIO_PEDIDO_RANGO_ETARIO_REPARTIDOR) REFERENCES CAFE61.BI_RANGOETARIO (RANGOETARIO_CODIGO);
GO
-- Tabla de Hechos Pedido
CREATE PROCEDURE CAFE61.BI_PEDIDO_CREAR
AS
SELECT * 
INTO cafe61.BI_PEDIDO
FROM cafe61.PEDIDO
--PK BI_PEDIDO
ALTER TABLE CAFE61.BI_PEDIDO
ADD CONSTRAINT PK_BI_PEDIDO_NUMERO
PRIMARY KEY (PEDIDO_NUMERO);
--Col Tiempo
ALTER TABLE CAFE61.BI_PEDIDO
ADD PEDIDO_TIEMPO INT;
--Agrego datos a Col TIEMPO
UPDATE CAFE61.BI_PEDIDO
SET PEDIDO_TIEMPO = t.tiempo_codigo
FROM CAFE61.BI_PEDIDO p
	INNER JOIN  CAFE61.BI_TIEMPO t 
		ON t.tiempo_anio = YEAR(p.PEDIDO_FECHA)
		AND t.tiempo_mes = MONTH(p.PEDIDO_FECHA)
		AND t.tiempo_dia = DATEPART(WEEKDAY, p.PEDIDO_FECHA)
		AND t.tiempo_franjahoraria = CONCAT(
            RIGHT('00' + CAST(DATEPART(HOUR, p.PEDIDO_FECHA) AS VARCHAR(2)), 2), ':00 - ', 
            RIGHT('00' + CAST(DATEPART(HOUR, p.PEDIDO_FECHA) + 2 AS VARCHAR(2)), 2), ':00'
        )
--FK a TIEMPO
ALTER TABLE CAFE61.BI_PEDIDO
ADD CONSTRAINT FK_BI_PEDIDO_TIEMPO
FOREIGN KEY (PEDIDO_TIEMPO) REFERENCES CAFE61.BI_TIEMPO (tiempo_codigo);
--FK a ESTADO
ALTER TABLE CAFE61.BI_PEDIDO
ADD CONSTRAINT FK_BI_PEDIDO_ESTADO
FOREIGN KEY (PEDIDO_ESTADO) REFERENCES CAFE61.BI_ESTADO_PEDIDO (PEDIDO_ESTADO_CODIGO);
--FK a LOCAL
ALTER TABLE CAFE61.BI_PEDIDO
ADD CONSTRAINT FK_BI_PEDIDO_LOCAL
FOREIGN KEY (PEDIDO_LOCAL) REFERENCES CAFE61.BI_LOCAL (LOCAL_CODIGO);
-- Col Tipo MP
ALTER TABLE CAFE61.BI_PEDIDO
ADD PEDIDO_TIPO_MEDIO_PAGO INT;
-- Agrego datos a Col Tipo MP
UPDATE CAFE61.BI_PEDIDO
SET PEDIDO_TIPO_MEDIO_PAGO = m.MEDIO_PAGO_TIPO
FROM CAFE61.BI_PEDIDO p
	INNER JOIN  CAFE61.MEDIO_PAGO m 
		ON m.MEDIO_PAGO_CODIGO = p.PEDIDO_MEDIO_PAGO
-- FK a TIPO MP
ALTER TABLE CAFE61.BI_PEDIDO
ADD CONSTRAINT FK_BI_PEDIDO_TIPO_MEDIO_PAGO
FOREIGN KEY (PEDIDO_TIPO_MEDIO_PAGO) REFERENCES CAFE61.BI_TIPO_MEDIO_PAGO (TIPO_MEDIO_PAGO_CODIGO);
-- Col RangoEtario
ALTER TABLE CAFE61.BI_PEDIDO
ADD PEDIDO_RANGO_ETARIO INT;
-- Agrego datos a Col RangoEtario
UPDATE CAFE61.BI_PEDIDO
SET PEDIDO_RANGO_ETARIO = e.RANGOETARIO_CODIGO
FROM CAFE61.BI_PEDIDO p
	INNER JOIN CAFE61.USUARIO u ON p.PEDIDO_USUARIO = u.USUARIO_CODIGO
	INNER JOIN CAFE61.BI_RANGOETARIO e ON DATEDIFF(year, u.USUARIO_FECHA_NAC, GETDATE()) BETWEEN e.RANGOETARIO_DESDE AND e.RANGOETARIO_HASTA;
-- FK a RangoEtario
ALTER TABLE CAFE61.BI_PEDIDO
ADD CONSTRAINT FK_BI_PEDIDO_RANGOETARIO
FOREIGN KEY (PEDIDO_RANGO_ETARIO) REFERENCES CAFE61.BI_RANGOETARIO (RANGOETARIO_CODIGO);
-- FK a ENVIOPEDIDO
ALTER TABLE CAFE61.BI_PEDIDO
ADD CONSTRAINT FK_BI_PEDIDO_ENVIO_PEDIDO
FOREIGN KEY (PEDIDO_ENVIO_PEDIDO) REFERENCES CAFE61.BI_ENVIO_PEDIDO (ENVIO_PEDIDO_CODIGO);
GO
-- Tabla de Hechos Reclamo
CREATE PROCEDURE cafe61.BI_RECLAMO_CREAR
AS
SELECT * 
INTO CAFE61.BI_RECLAMO
FROM CAFE61.RECLAMO
--PK BI_RECLAMO
ALTER TABLE CAFE61.BI_RECLAMO
ADD CONSTRAINT PK_BI_RECLAMO_NUMERO
PRIMARY KEY (RECLAMO_NUMERO);
--Col Tiempo
ALTER TABLE CAFE61.BI_RECLAMO
ADD RECLAMO_TIEMPO INT;
--Agrego datos a Col TIEMPO
UPDATE CAFE61.BI_RECLAMO
SET RECLAMO_TIEMPO = t.tiempo_codigo
FROM CAFE61.BI_RECLAMO r
	INNER JOIN  CAFE61.BI_TIEMPO t 
		ON t.tiempo_anio = YEAR(r.RECLAMO_FECHA)
		AND t.tiempo_mes = MONTH(r.RECLAMO_FECHA)
		AND t.tiempo_dia = DATEPART(WEEKDAY, r.RECLAMO_FECHA)
		AND t.tiempo_franjahoraria = CONCAT(
            RIGHT('00' + CAST(DATEPART(HOUR, r.RECLAMO_FECHA) AS VARCHAR(2)), 2), ':00 - ', 
            RIGHT('00' + CAST(DATEPART(HOUR, r.RECLAMO_FECHA) + 2 AS VARCHAR(2)), 2), ':00'
        )
--FK a TIEMPO
ALTER TABLE CAFE61.BI_RECLAMO
ADD CONSTRAINT FK_BI_RECLAMO_TIEMPO
FOREIGN KEY (RECLAMO_TIEMPO) REFERENCES CAFE61.BI_TIEMPO (tiempo_codigo);
-- Col RangoEtarioOperador
ALTER TABLE CAFE61.BI_RECLAMO
ADD RECLAMO_RANGO_ETARIO_OPERADOR INT;
-- Agrego datos a Col RangoEtarioOperador
UPDATE CAFE61.BI_RECLAMO
SET RECLAMO_RANGO_ETARIO_OPERADOR = e.RANGOETARIO_CODIGO
FROM CAFE61.BI_RECLAMO r
	INNER JOIN CAFE61.OPERADOR_RECLAMO o ON r.RECLAMO_OPERADOR = o.OPERADOR_CODIGO
	INNER JOIN CAFE61.BI_RANGOETARIO e ON DATEDIFF(year, o.OPERADOR_RECLAMO_FECHA_NAC, GETDATE()) BETWEEN e.RANGOETARIO_DESDE AND e.RANGOETARIO_HASTA;
-- FK a RangoEtarioOperador
ALTER TABLE CAFE61.BI_RECLAMO
ADD CONSTRAINT FK_BI_RECLAMO_RANGO_ETARIO_OPERADOR
FOREIGN KEY (RECLAMO_RANGO_ETARIO_OPERADOR) REFERENCES CAFE61.BI_RANGOETARIO (RANGOETARIO_CODIGO);
-- FK a Tipo Reclamo
ALTER TABLE CAFE61.BI_RECLAMO
ADD CONSTRAINT FK_BI_RECLAMO_TIPO
FOREIGN KEY (RECLAMO_TIPO) REFERENCES CAFE61.BI_TIPO_RECLAMO (TIPO_RECLAMO_CODIGO);
-- FK a PEDIDO 
ALTER TABLE CAFE61.BI_RECLAMO
ADD CONSTRAINT FK_BI_RECLAMO_PEDIDO_NUMERO
FOREIGN KEY (RECLAMO_PEDIDO_NUMERO) REFERENCES CAFE61.BI_PEDIDO (PEDIDO_NUMERO);
GO
-- Tabla de Hechos Envio Mensajeria
CREATE PROCEDURE cafe61.BI_ENVIO_MENSAJERIA_CREAR
AS
SELECT * 
INTO CAFE61.BI_ENVIO_MENSAJERIA
FROM CAFE61.ENVIO_MENSAJERIA
--PK BI_PEDIDO
ALTER TABLE cafe61.BI_ENVIO_MENSAJERIA
ADD CONSTRAINT PK_BI_ENVIO_MENSAJERIA_NUMERO
PRIMARY KEY (ENVIO_MENSAJERIA_NUMERO);
--Col Tiempo
ALTER TABLE CAFE61.BI_ENVIO_MENSAJERIA
ADD ENVIO_MENSAJERIA_TIEMPO INT;
--Agrego datos a Col TIEMPO
UPDATE CAFE61.BI_ENVIO_MENSAJERIA
SET ENVIO_MENSAJERIA_TIEMPO = t.tiempo_codigo
FROM CAFE61.BI_ENVIO_MENSAJERIA e
	INNER JOIN  CAFE61.BI_TIEMPO t 
		ON t.tiempo_anio = YEAR(e.ENVIO_MENSAJERIA_FECHA_PEDIDO)
		AND t.tiempo_mes = MONTH(e.ENVIO_MENSAJERIA_FECHA_PEDIDO)
		AND t.tiempo_dia = DATEPART(WEEKDAY, e.ENVIO_MENSAJERIA_FECHA_PEDIDO)
		AND t.tiempo_franjahoraria = CONCAT(
            RIGHT('00' + CAST(DATEPART(HOUR, e.ENVIO_MENSAJERIA_FECHA_PEDIDO) AS VARCHAR(2)), 2), ':00 - ', 
            RIGHT('00' + CAST(DATEPART(HOUR, e.ENVIO_MENSAJERIA_FECHA_PEDIDO) + 2 AS VARCHAR(2)), 2), ':00'
        )
--FK a TIEMPO
ALTER TABLE cafe61.BI_ENVIO_MENSAJERIA
ADD CONSTRAINT FK_BI_ENVIO_MENSAJERIA_TIEMPO
FOREIGN KEY (ENVIO_MENSAJERIA_TIEMPO) REFERENCES CAFE61.BI_TIEMPO (tiempo_codigo)
--FK a Paquete
ALTER TABLE cafe61.BI_ENVIO_MENSAJERIA
ADD CONSTRAINT FK_BI_ENVIO_MENSAJERIA_PAQUETE
FOREIGN KEY (ENVIO_MENSAJERIA_PAQUETE) REFERENCES CAFE61.BI_PAQUETE (paquete_codigo)
-- Col RangoEtarioRepartidor
ALTER TABLE CAFE61.BI_ENVIO_MENSAJERIA
ADD ENVIO_MENSAJERIA_RETARIO_REPARTIDOR INT
-- Agrego datos a Col RangoEtarioRepartidor
UPDATE CAFE61.BI_ENVIO_MENSAJERIA
SET ENVIO_MENSAJERIA_RETARIO_REPARTIDOR = re.RANGOETARIO_CODIGO
FROM CAFE61.BI_ENVIO_MENSAJERIA e
	INNER JOIN CAFE61.REPARTIDOR r ON e.ENVIO_MENSAJERIA_REPARTIDOR = r.REPARTIDOR_CODIGO
	INNER JOIN CAFE61.BI_RANGOETARIO re ON DATEDIFF(year, r.REPARTIDOR_FECHA_NAC, GETDATE()) BETWEEN re.RANGOETARIO_DESDE AND re.RANGOETARIO_HASTA
-- FK a RangoEtarioRepartidor
ALTER TABLE CAFE61.BI_ENVIO_MENSAJERIA
ADD CONSTRAINT FK_BI_ENVIO_MENSAJERIA_RETARIO_REPARTIDOR
FOREIGN KEY (ENVIO_MENSAJERIA_RETARIO_REPARTIDOR) REFERENCES CAFE61.BI_RANGOETARIO (RANGOETARIO_CODIGO)
-- FK a Repartidor
ALTER TABLE CAFE61.BI_ENVIO_MENSAJERIA
ADD CONSTRAINT FK_BI_ENVIO_MENSAJERIA_REPARTIDOR
FOREIGN KEY (ENVIO_MENSAJERIA_REPARTIDOR) REFERENCES CAFE61.BI_REPARTIDOR (REPARTIDOR_CODIGO)
go

--Creacion de modelo BI
exec cafe61.BI_LimpiezaEsquema
exec cafe61.BI_PROVINCIA_CREAR
exec cafe61.BI_LOCALIDAD_CREAR
exec cafe61.BI_TIPO_MEDIO_PAGO_CREAR
exec cafe61.BI_LOCAL_TIPO_CREAR
exec cafe61.BI_LOCAL_CREAR
exec cafe61.BI_TIPO_MOVILIDAD_CREAR
exec cafe61.BI_TIPO_PAQUETE_CREAR
exec cafe61.BI_PAQUETE_CREAR
exec cafe61.BI_ESTADO_PEDIDO_CREAR
exec cafe61.BI_ENVIO_MENSAJERIA_ESTADO_CREAR
exec cafe61.BI_RECLAMO_ESTADO_CREAR
exec cafe61.BI_TIPO_RECLAMO_CREAR
exec cafe61.BI_TIEMPO_CREAR
exec CAFE61.BI_RANGOETARIO_CREAR
exec CAFE61.BI_REPARTIDOR_CREAR
exec CAFE61.BI_ENVIO_PEDIDO_CREAR
exec CAFE61.BI_PEDIDO_CREAR
exec cafe61.BI_RECLAMO_CREAR
exec cafe61.BI_ENVIO_MENSAJERIA_CREAR
GO
/* Promedio mensual del valor asegurado (valor declarado por el usuario) de
los paquetes enviados a través del servicio de mensajería en función del
tipo de paquete.*/
CREATE VIEW CAFE61.BI_VIEW_PROM_VALOR_ASEGURADO
AS
SELECT 
	t.tiempo_mes Mes,
	tp.PAQUETE_TIPO_CODIGO TipoPaqueteCod,
	tp.PAQUETE_TIPO_PRECIO TipoPaquete,
	AVG(e.ENVIO_MENSAJERIA_PRECIO_SEGURO) PromedioValorAsegurado
FROM CAFE61.BI_ENVIO_MENSAJERIA e
	JOIN CAFE61.BI_TIEMPO t ON t.tiempo_codigo = e.ENVIO_MENSAJERIA_TIEMPO
	JOIN CAFE61.BI_PAQUETE p ON p.PAQUETE_CODIGO = e.ENVIO_MENSAJERIA_PAQUETE
	JOIN CAFE61.BI_TIPO_PAQUETE tp ON p.PAQUETE_TIPO = tp.PAQUETE_TIPO_CODIGO
GROUP BY 
	t.tiempo_mes,
	tp.PAQUETE_TIPO_CODIGO,
	tp.PAQUETE_TIPO_PRECIO
go
/*Desvío promedio en tiempo de entrega según el tipo de movilidad, el día
de la semana y la franja horaria.
El desvío debe calcularse en minutos y representa la diferencia entre la
fecha/hora en que se realizó el pedido y la fecha/hora que se entregó en
comparación con los minutos de tiempo estimados.
Este indicador debe tener en cuenta todos los envíos, es decir, sumar tanto
los envíos de pedidos como los de mensajería. FALTA CORREGIR O HACERLA*/
CREATE VIEW CAFE61.BI_VIEW_DESVIO_PROM_TIEMPO_ENTREGA
AS
WITH CTE AS (
SELECT 
	t.tiempo_dia Dia,
	t.tiempo_franjahoraria FranjaHoraria,
	tm.TIPO_MOVILIDAD_CODIGO TipoMovilidadCod,
	tm.TIPO_MOVILIDAD_DESCRIPCION TipoMovilidad,
	DATEDIFF(minute, e.ENVIO_MENSAJERIA_FECHA_ESTIMADO, e.ENVIO_MENSAJERIA_FECHA_ENTREGA) MinutosDemora
FROM CAFE61.BI_ENVIO_MENSAJERIA e
	JOIN CAFE61.BI_TIEMPO t ON t.tiempo_codigo = e.ENVIO_MENSAJERIA_TIEMPO
	JOIN CAFE61.BI_REPARTIDOR r ON r.REPARTIDOR_CODIGO = e.ENVIO_MENSAJERIA_REPARTIDOR
	JOIN CAFE61.BI_TIPO_MOVILIDAD tm ON r.REPARTIDOR_TIPO_MOVILIDAD = tm.TIPO_MOVILIDAD_CODIGO
GROUP BY 
	t.tiempo_dia,
	t.tiempo_franjahoraria,
	tm.TIPO_MOVILIDAD_CODIGO,
	tm.TIPO_MOVILIDAD_DESCRIPCION,
	DATEDIFF(minute, e.ENVIO_MENSAJERIA_FECHA_ESTIMADO, e.ENVIO_MENSAJERIA_FECHA_ENTREGA)
UNION
	SELECT 
	t.tiempo_dia Dia,
	t.tiempo_franjahoraria FranjaHoraria,
	tm.TIPO_MOVILIDAD_CODIGO TipoMovilidadCod,
	tm.TIPO_MOVILIDAD_DESCRIPCION TipoMovilidad,
	DATEDIFF(minute, DATEADD(minute, e.ENVIO_PEDIDO_TIEMPO_ESTIMADO_ENTREGA, p.PEDIDO_FECHA), e.ENVIO_PEDIDO_FECHA_ENTREGA) MinutosDemora
FROM CAFE61.BI_PEDIDO p
	JOIN CAFE61.BI_TIEMPO t ON t.tiempo_codigo = p.PEDIDO_TIEMPO
	JOIN CAFE61.BI_ENVIO_PEDIDO e ON p.PEDIDO_ENVIO_PEDIDO = e.ENVIO_PEDIDO_CODIGO
	JOIN CAFE61.BI_REPARTIDOR r ON r.REPARTIDOR_CODIGO = e.ENVIO_PEDIDO_REPARTIDOR
	JOIN CAFE61.BI_TIPO_MOVILIDAD tm ON r.REPARTIDOR_TIPO_MOVILIDAD = tm.TIPO_MOVILIDAD_CODIGO
GROUP BY 
	t.tiempo_dia,
	t.tiempo_franjahoraria,
	tm.TIPO_MOVILIDAD_CODIGO,
	tm.TIPO_MOVILIDAD_DESCRIPCION,
	DATEDIFF(minute, DATEADD(minute, e.ENVIO_PEDIDO_TIEMPO_ESTIMADO_ENTREGA, p.PEDIDO_FECHA), e.ENVIO_PEDIDO_FECHA_ENTREGA)
)
SELECT Dia, FranjaHoraria, TipoMovilidadCod, TipoMovilidad, AVG(MinutosDemora) MinutosDemoraPromedio
FROM CTE
GROUP BY Dia, FranjaHoraria, TipoMovilidadCod, TipoMovilidad
go
/*Porcentaje de pedidos y mensajería entregados mensualmente según el
rango etario de los repartidores y la localidad.
Este indicador se debe tener en cuenta y sumar tanto los envíos de pedidos
como los de mensajería.
El porcentaje se calcula en función del total general de pedidos y envíos
mensuales entregados. FALTA CORREGIR O HACERLA*/
CREATE VIEW CAFE61.BI_VIEW_PORCENTAJE_PED_MENS
AS
	SELECT T.tiempo_anio as [Año],
	T.tiempo_mes AS [Mes],
	PED.PEDIDO_RANGO_ETARIO as [Rango etario],
	L.LOCAL_LOCALIDAD as [Localidad],
	CAST(COUNT(distinct PED.PEDIDO_NUMERO)AS decimal(18,2)) /(select COUNT(distinct PEDIDO_NUMERO) from CAFE61.BI_PEDIDO
											join CAFE61.BI_TIEMPO on tiempo_codigo = PEDIDO_TIEMPO
											WHERE PEDIDO_ESTADO = 1  AND T.tiempo_anio = tiempo_anio and T.tiempo_mes = tiempo_mes
											group by tiempo_anio,
											tiempo_mes) * 100.00 as [Porcentaje de entregados]
	FROM CAFE61.BI_PEDIDO AS PED
	join CAFE61.BI_TIEMPO as T on PED.PEDIDO_TIEMPO = T.tiempo_codigo
	join CAFE61.BI_LOCAL as L on L.LOCAL_CODIGO = PED.PEDIDO_LOCAL
	WHERE PED.PEDIDO_ESTADO = 1
	group by tiempo_anio,
	tiempo_mes,
	PEDIDO_RANGO_ETARIO,
	LOCAL_LOCALIDAD
go
SELECT * FROM CAFE61.BI_ESTADO_PEDIDO




/*Día de la semana y franja horaria con mayor cantidad de pedidos según la
localidad y categoría del local, para cada mes de cada año*/
CREATE VIEW CAFE61.BI_VIEW_CANT_PEDIDO
AS
WITH CTE AS (
SELECT	
	t.tiempo_anio Anio,
	t.tiempo_mes Mes,
	l.LOCAL_LOCALIDAD Localidad,
	l.LOCAL_TIPO Categoria,
	t.tiempo_dia DiaSemana,
	t.tiempo_franjahoraria FranjaHoraria,
	COUNT(*) as CantidadPedidos,
	ROW_NUMBER() OVER (PARTITION BY t.tiempo_anio, t.tiempo_mes, l.LOCAL_LOCALIDAD, l.LOCAL_TIPO 
                           ORDER BY COUNT(*) DESC) AS RowNum

FROM CAFE61.BI_PEDIDO p
	JOIN CAFE61.BI_TIEMPO t ON t.tiempo_codigo = p.PEDIDO_TIEMPO
	JOIN CAFE61.BI_LOCAL l ON l.LOCAL_CODIGO = p.PEDIDO_LOCAL
GROUP BY 
	t.tiempo_anio,
	t.tiempo_mes,
	t.tiempo_dia,
	t.tiempo_franjahoraria,
	l.LOCAL_LOCALIDAD,
	l.LOCAL_TIPO
)
SELECT Anio, Mes, Localidad, Categoria, DiaSemana, FranjaHoraria, CantidadPedidos, RowNum
FROM CTE
WHERE RowNum = 1
go
/*Monto total no cobrado por cada local en función de los pedidos
cancelados según el día de la semana y la franja horaria (cuentan como
pedidos cancelados tanto los que cancela el usuario como el local).
*/
CREATE VIEW CAFE61.BI_VIEW_TOTAL_NO_COBRADO
AS
SELECT	
	l.LOCAL_CODIGO Local_Codigo,
	l.LOCAL_NOMBRE Local_Categoria,
	t.tiempo_dia DiaSemana,
	t.tiempo_franjahoraria FranjaHoraria,
	ISNULL(SUM(p.PEDIDO_TOTAL_SERVICIO),0) AS MontoNoCobrado
FROM CAFE61.BI_PEDIDO p
	JOIN CAFE61.BI_TIEMPO t ON t.tiempo_codigo = p.PEDIDO_TIEMPO
	JOIN CAFE61.BI_LOCAL l ON l.LOCAL_CODIGO = p.PEDIDO_LOCAL
WHERE p.PEDIDO_ESTADO = 2
GROUP BY 
	l.LOCAL_CODIGO,
	l.LOCAL_NOMBRE,
	t.tiempo_dia,
	t.tiempo_franjahoraria
go
/*Valor promedio mensual que tienen los envíos de pedidos en cada
localidad.
*/
CREATE VIEW CAFE61.BI_VIEW_PROM_ENVIO_PEDIDO
AS
SELECT
	t.tiempo_mes Mes,
	l.LOCAL_LOCALIDAD Localidad,
	AVG(e.ENVIO_PEDIDO_PRECIO_ENVIO) PromedioValorEnvio
FROM CAFE61.BI_PEDIDO p
	JOIN CAFE61.BI_TIEMPO t ON t.tiempo_codigo = p.PEDIDO_TIEMPO
	JOIN CAFE61.BI_ENVIO_PEDIDO e ON e.ENVIO_PEDIDO_CODIGO = p.PEDIDO_ENVIO_PEDIDO
	JOIN CAFE61.BI_LOCAL l ON l.LOCAL_CODIGO = p.PEDIDO_LOCAL
GROUP BY 
	t.tiempo_mes,
	l.LOCAL_LOCALIDAD
go
/*Monto total de los cupones utilizados por mes en función del rango etario
de los usuarios*/
CREATE VIEW CAFE61.BI_VIEW_TOTAL_CUPONES
AS
SELECT
	r.RANGOETARIO_CODIGO RangoEtario,
	r.RANGOETARIO_DESDE Desde,
	r.RANGOETARIO_HASTA Hasta,
	t.tiempo_mes Mes,
	ISNULL(SUM(p.PEDIDO_TOTAL_CUPONES),0) MontoTotalCupones
FROM CAFE61.BI_PEDIDO p
	JOIN CAFE61.BI_TIEMPO t ON t.tiempo_codigo = p.PEDIDO_TIEMPO
	JOIN CAFE61.BI_RANGOETARIO r ON r.RANGOETARIO_CODIGO = p.PEDIDO_RANGO_ETARIO 
GROUP BY 
	r.RANGOETARIO_CODIGO,
	r.RANGOETARIO_DESDE,
	r.RANGOETARIO_HASTA,
	t.tiempo_mes
go
/*Promedio de calificación mensual por local.*/
CREATE VIEW CAFE61.BI_VIEW_PROM_CALIFICACION
AS
SELECT 
	l.LOCAL_CODIGO CodLocal,
	l.LOCAL_NOMBRE NombreLocal,
	t.tiempo_mes Mes,
	CAST(ISNULL(AVG(p.PEDIDO_CALIFICACION), 0) AS decimal(10,1)) PromedioCalificacion
FROM CAFE61.BI_PEDIDO p
	JOIN CAFE61.BI_TIEMPO t ON t.tiempo_codigo = p.PEDIDO_TIEMPO
	JOIN CAFE61.BI_LOCAL l ON l.LOCAL_CODIGO = p.PEDIDO_LOCAL
GROUP BY 
	l.LOCAL_CODIGO,
	l.LOCAL_NOMBRE,
	t.tiempo_mes
go
/*Cantidad de reclamos mensuales recibidos por cada local en función del
día de la semana y rango horario.*/
CREATE VIEW CAFE61.BI_VIEW_CANT_RECLAMO_LOCAL
AS
SELECT	
	l.LOCAL_CODIGO Local_Codigo, --- TRAJE AL LOCAL AL RECLAMO, OTRA POSIBLE SOLUCION ERA TRAERLO ATRAVEZ DEL PEDIDO// Definimos en traer lo de Atravez de pedido
	l.LOCAL_NOMBRE Local_Categoria,
	t.tiempo_mes Mes,
	t.tiempo_dia DiaSemana,
	t.tiempo_franjahoraria FranjaHoraria,
	COUNT(*) CantidadReclamo
FROM CAFE61.BI_RECLAMO r
	JOIN CAFE61.BI_TIEMPO t ON t.tiempo_codigo = r.RECLAMO_TIEMPO
	JOIN CAFE61.BI_PEDIDO p ON p.PEDIDO_NUMERO = r.RECLAMO_PEDIDO_NUMERO
	JOIN CAFE61.BI_LOCAL l ON l.LOCAL_CODIGO = p.PEDIDO_LOCAL
GROUP BY 
	l.LOCAL_CODIGO,
	l.LOCAL_NOMBRE,
	t.tiempo_mes,
	t.tiempo_dia,
	t.tiempo_franjahoraria
go
/*Tiempo promedio de resolución de reclamos mensual según cada tipo de
reclamo y rango etario de los operadores.
El tiempo de resolución debe calcularse en minutos y representa la
diferencia entre la fecha/hora en que se realizó el reclamo y la fecha/hora
que se resolvió.*/
CREATE VIEW CAFE61.BI_VIEW_TIEMPO_PROM_SOLUCION_RECLAMO
AS
SELECT	
	t.TIPO_RECLAMO_CODIGO TipoCod,
	t.TIPO_RECLAMO_DESCRIPCION Tipo,
	e.RANGOETARIO_CODIGO RangoEtarioCod,
	e.RANGOETARIO_DESDE Desde,
	e.RANGOETARIO_HASTA Hasta,
	AVG(DATEDIFF(minute, r.RECLAMO_FECHA, r.RECLAMO_FECHA_SOLUCION))TiempoResolucionPromedioMinutos
FROM CAFE61.BI_RECLAMO r
	JOIN CAFE61.BI_TIPO_RECLAMO t ON t.TIPO_RECLAMO_CODIGO = r.RECLAMO_TIPO
	JOIN CAFE61.BI_RANGOETARIO e ON e.RANGOETARIO_CODIGO = r.RECLAMO_RANGO_ETARIO_OPERADOR
GROUP BY 
	t.TIPO_RECLAMO_CODIGO,
	t.TIPO_RECLAMO_DESCRIPCION,
	e.RANGOETARIO_CODIGO,
	e.RANGOETARIO_DESDE,
	e.RANGOETARIO_HASTA
go
/*Monto mensual generado en cupones a partir de reclamos.*/
CREATE VIEW CAFE61.BI_VIEW_MONTO_RECLAMO_CUPONES
AS
SELECT	
	t.tiempo_mes Mes,
	ISNULL(SUM(p.PEDIDO_TOTAL_CUPONES),0) [Monto mensual generado en cupones]
FROM CAFE61.BI_RECLAMO r
	JOIN CAFE61.BI_TIEMPO t ON t.tiempo_codigo = r.RECLAMO_TIEMPO
	JOIN CAFE61.BI_PEDIDO p ON p.PEDIDO_NUMERO = r.RECLAMO_PEDIDO_NUMERO
GROUP BY 
	t.tiempo_mes
 go