/*Monto total de los cupones utilizados por mes en función del rango etario
de los usuarios*/

SELECT
	CASE
        WHEN DATEDIFF(YEAR, u.USUARIO_FECHA_NAC, GETDATE()) < 25 THEN '<25'
        WHEN DATEDIFF(YEAR, u.USUARIO_FECHA_NAC, GETDATE()) BETWEEN 25 AND 35 THEN '25 - 35'
        WHEN DATEDIFF(YEAR, u.USUARIO_FECHA_NAC, GETDATE()) BETWEEN 35 AND 55 THEN '35 - 55'
        ELSE '>55'
    END AS RangoEtario,
	MONTH(ped.PEDIDO_FECHA) Mes,
	ISNULL(SUM(ped.PEDIDO_TOTAL_CUPONES),0) MontoTotalCupones
FROM CAFE61.PEDIDO ped
	JOIN CAFE61.USUARIO u ON u.USUARIO_CODIGO = ped.PEDIDO_USUARIO
GROUP BY 
	CASE
        WHEN DATEDIFF(YEAR, u.USUARIO_FECHA_NAC, GETDATE()) < 25 THEN '<25'
        WHEN DATEDIFF(YEAR, u.USUARIO_FECHA_NAC, GETDATE()) BETWEEN 25 AND 35 THEN '25 - 35'
        WHEN DATEDIFF(YEAR, u.USUARIO_FECHA_NAC, GETDATE()) BETWEEN 35 AND 55 THEN '35 - 55'
        ELSE '>55'
    END,
    MONTH(ped.PEDIDO_FECHA)
ORDER BY RangoEtario,Mes