/*Promedio de calificación mensual por local.*/

SELECT 
	l.LOCAL_CODIGO CodLocal,
	l.LOCAL_NOMBRE NombreLocal,
	MONTH(ped.PEDIDO_FECHA) Mes,
	CAST(ISNULL(AVG(ped.PEDIDO_CALIFICACION), 0) AS decimal(10,1)) PromedioCalificacion
FROM CAFE61.LOCAL l
	LEFT JOIN CAFE61.PEDIDO ped ON ped.PEDIDO_LOCAL = l.LOCAL_CODIGO
GROUP BY 
	l.LOCAL_CODIGO,l.LOCAL_NOMBRE,MONTH(ped.PEDIDO_FECHA)
ORDER BY l.LOCAL_CODIGO,L.LOCAL_NOMBRE,MONTH(ped.PEDIDO_FECHA)