/*Valor promedio mensual que tienen los envíos de pedidos en cada
localidad.*/

SELECT
	l.LOCAL_LOCALIDAD,
	MONTH(ped.PEDIDO_FECHA) Mes,
	ISNULL(AVG(e.ENVIO_PEDIDO_PRECIO_ENVIO),0) Precio_Envio
FROM CAFE61.LOCAL l
	LEFT JOIN CAFE61.PEDIDO ped ON l.LOCAL_CODIGO = ped.PEDIDO_LOCAL
	LEFT JOIN CAFE61.ENVIO_PEDIDO e ON e.ENVIO_PEDIDO_CODIGO = ped.PEDIDO_ENVIO_PEDIDO
GROUP BY l.LOCAL_LOCALIDAD,MONTH(ped.PEDIDO_FECHA)

