CREATE PROCEDURE CAFE61.BI_PEDIDO_CREAR
AS
SELECT * 
INTO cafe61.BI_PEDIDO
FROM cafe61.PEDIDO
GO

--PK BI_PEDIDO
ALTER TABLE CAFE61.BI_PEDIDO
ADD CONSTRAINT PK_BI_PEDIDO_NUMERO
PRIMARY KEY (PEDIDO_NUMERO);
GO

--Col Tiempo
ALTER TABLE CAFE61.BI_PEDIDO
ADD PEDIDO_TIEMPO INT;
GO

--Agrego datos a Col TIEMPO
UPDATE CAFE61.BI_PEDIDO
SET PEDIDO_TIEMPO = t.tiempo_codigo
FROM CAFE61.BI_PEDIDO p
	INNER JOIN  CAFE61.BI_TIEMPO t 
		ON t.tiempo_anio = YEAR(p.PEDIDO_FECHA)
		AND t.tiempo_mes = MONTH(p.PEDIDO_FECHA)
		AND t.tiempo_dia = DATEPART(WEEKDAY, p.PEDIDO_FECHA)
		AND t.tiempo_franjahoraria = CONCAT(
            RIGHT('00' + CAST(DATEPART(HOUR, p.PEDIDO_FECHA) AS VARCHAR(2)), 2), ':00 - ', 
            RIGHT('00' + CAST(DATEPART(HOUR, p.PEDIDO_FECHA) + 2 AS VARCHAR(2)), 2), ':00'
        )
GO

--FK a TIEMPO
ALTER TABLE CAFE61.BI_PEDIDO
ADD CONSTRAINT FK_BI_PEDIDO_TIEMPO
FOREIGN KEY (PEDIDO_TIEMPO) REFERENCES CAFE61.BI_TIEMPO (tiempo_codigo);
GO

--FK a ESTADO
ALTER TABLE CAFE61.BI_PEDIDO
ADD CONSTRAINT FK_BI_PEDIDO_ESTADO
FOREIGN KEY (PEDIDO_ESTADO) REFERENCES CAFE61.BI_ESTADO_PEDIDO (PEDIDO_ESTADO_CODIGO);
GO

--FK a LOCAL
ALTER TABLE CAFE61.BI_PEDIDO
ADD CONSTRAINT FK_BI_PEDIDO_LOCAL
FOREIGN KEY (PEDIDO_LOCAL) REFERENCES CAFE61.BI_LOCAL (LOCAL_CODIGO);
GO

-- Col Tipo MP
ALTER TABLE CAFE61.BI_PEDIDO
ADD PEDIDO_TIPO_MEDIO_PAGO INT;
GO

-- Agrego datos a Col Tipo MP
UPDATE CAFE61.BI_PEDIDO
SET PEDIDO_TIPO_MEDIO_PAGO = m.MEDIO_PAGO_TIPO
FROM CAFE61.BI_PEDIDO p
	INNER JOIN  CAFE61.MEDIO_PAGO m 
		ON m.MEDIO_PAGO_CODIGO = p.PEDIDO_MEDIO_PAGO
GO

-- FK a TIPO MP
ALTER TABLE CAFE61.BI_PEDIDO
ADD CONSTRAINT FK_BI_PEDIDO_TIPO_MEDIO_PAGO
FOREIGN KEY (PEDIDO_TIPO_MEDIO_PAGO) REFERENCES CAFE61.BI_TIPO_MEDIO_PAGO (TIPO_MEDIO_PAGO_CODIGO);


-- Col RangoEtario
ALTER TABLE CAFE61.BI_PEDIDO
ADD PEDIDO_RANGO_ETARIO INT;
GO

-- Agrego datos a Col RangoEtario
UPDATE CAFE61.BI_PEDIDO
SET PEDIDO_RANGO_ETARIO = e.RANGOETARIO_CODIGO
FROM CAFE61.BI_PEDIDO p
	INNER JOIN CAFE61.USUARIO u ON p.PEDIDO_USUARIO = u.USUARIO_CODIGO
	INNER JOIN CAFE61.BI_RANGOETARIO e ON DATEDIFF(year, u.USUARIO_FECHA_NAC, GETDATE()) BETWEEN e.RANGOETARIO_DESDE AND e.RANGOETARIO_HASTA;
GO

-- FK a RangoEtario
ALTER TABLE CAFE61.BI_PEDIDO
ADD CONSTRAINT FK_BI_PEDIDO_RANGOETARIO
FOREIGN KEY (PEDIDO_RANGO_ETARIO) REFERENCES CAFE61.BI_RANGOETARIO (RANGOETARIO_CODIGO);

-- FK a ENVIOPEDIDO
ALTER TABLE CAFE61.BI_PEDIDO
ADD CONSTRAINT FK_BI_PEDIDO_ENVIO_PEDIDO
FOREIGN KEY (PEDIDO_ENVIO_PEDIDO) REFERENCES CAFE61.BI_ENVIO_PEDIDO (ENVIO_PEDIDO_CODIGO);


SELECT * FROM CAFE61.BI_PEDIDO
SELECT * FROM CAFE61.BI_TIPO_MEDIO_PAGO